---
title: "Derivación bajo el signo integral"
author: "Juan Gabriel Gomila, Arnau Mir y Llorenç Valverde"
date: ''
output:
  beamer_presentation:
    incremental: yes
    theme: Warsaw
    toc: no
  ioslides_presentation:
    incremental: yes
  slidy_presentation:
    incremental: yes
header-includes: \usepackage{amsmath,color,array,booktabs,algorithm2e} \newcommand\blue[1]{\textcolor{blue}{#1}}
  \newcommand\red[1]{\textcolor{red}{#1}}
---


# Derivación bajo el signo integral

## Introducción

En esta presentación vamos a combinar lo aprendido en el capítulo de \blue{derivación} y en el de \blue{integración} con el objetivo de hallar la derivada de funciones del tipo:
$$
F(x)=\int_{g(x)}^{h(x)}f(t)\,dt.
$$
donde $f(x)$, $g(x)$ y $h(x)$ son funciones reales de variable real.

Antes de proceder con su resolución, veamos un ejemplo ilustrativo:

## Introducción
Consideremos la función siguiente para valores $x>0$:
$$
F(x)=\int_{x}^{x^2}\sin t\, dt,
$$
es decir el \red{área} de la función $\sin x$ entre dos valores que van cambiando con la variable $x$: los valores $x$ y $x^2$.

## Introducción
```{r,echo=FALSE,eval=FALSE}
library(shiny)
runApp("IntegralSinx")
```

## Introducción
Nos preguntamos cuál es la expresión de la \red{derivada} de la función $F(x)$:
$$
F(x)=\int_{g(x)}^{h(x)}f(t)\,dt.
$$

El siguiente resultado nos da la solución a nuestro problema.

## Derivada de una función bajo el signo integral
\begin{theorem}
Sea $f:D\longrightarrow\mathbb{R}$ una función continua siendo $D$ su \blue{dominio de definición.} Sean $g,h:[a,b]\longrightarrow\mathbb{R}$ funciones derivables tales que $g([a,b])\subseteq D$, $h([a,b])\subseteq D$. Definimos la función 
$$
F(x)=\int_{g(x)}^{h(x)} f(t)\,dt.
$$
Entonces $F$ es \red{derivable} y el valor de su \red{función derivada $F'(x)$} puede expresarse como:
$$
F'(x)=f(h(x))\cdot h'(x)-f(g(x))\cdot g'(x).
$$
\end{theorem}

## Derivada de una función bajo el signo integral
\begin{block}{Demostración.}

Usando las propiedades de la integral de una función podemos escribir la función $F(x)$ como:
\begin{equation}
F(x)=\int_{a}^{h(x)} f(t)\,dt-\int_a^{g(x)}f(t)\,dt,
\label{FDIF}
\end{equation}
siendo $a\in D$.
\end{block}

## Derivada de una función bajo el signo integral

\begin{block}{}
Para demostrar la proposición anterior basta demostrar que la derivada de las funciones:
$$
H(x)=\int_{a}^{h(x)} f(t)\,dt,\quad G(x)=\int_{a}^{g(x)} f(t)\,dt
$$
valen, respectivamente,
$$
H'(x)=f(h(x))\cdot h'(x),\quad G'(x)=f(g(x))\cdot g'(x),
$$
ya que usando la expresión (\ref{FDIF}), podemos escribir la derivada de la función $F(x)$ como:
$$
F'(x)=H'(x)-G'(x)=f(h(x))\cdot h'(x)-f(g(x))\cdot g'(x).
$$
\end{block}

## Derivada de una función bajo el signo integral

\begin{block}{}
Para ver las expresiones de las derivadas de las funciones $H(x)$ y $G(x)$, basta ver la expresión por ejemplo de $H'(x)$ ya que la otra, la expresión de $G'(x)$, se obtendría cambiando los papeles de la función $h(x)$ por $g(x)$.


Veamos pues que $\displaystyle H'(x)=f(h(x))\cdot h'(x)$. 

Notemos en primer lugar que podemos escribir la función $H(x)$ como la composición de las funciones siguientes:
$H(x)=(\hat{F}\circ h)(x),$ siendo $\displaystyle \hat{F}(x)=\int_a^x f(t)\,dt$. Efectivamente,
$$
(\hat{F}\circ h)(x)=\hat{F}(h(x))=\int_a^{h(x)}f(t)\,dt = H(x).
$$
\end{block}

## Derivada de una función bajo el signo integral

\begin{block}{}
Aplicando la regla de la cadena obtenemos,
$$
H'(x)=\hat{F}'(h(x))\cdot h'(x),
$$
pero usando el Teorema Fundamental del cálculo, tenemos que $\hat{F}'(z)=f(z)$. Por tanto, cambiando $z$ por $h(x)$, tenemos lo que queríamos demostrar:
$$
H'(x)=f(h(x))\cdot h'(x).
$$
\ \hfill $\Box$
\end{block}

## Ejemplo
Calculemos, usando el resultado anterior, la derivada de la función que introdujimos al principio de esta presentación:
$$
F(x)=\int_x^{x^2}\sin x\, dx.
$$

En este caso, $g(x)=x,\ h(x)=x^2$ y $f(x)=\sin x$. Entonces:
$$
\begin{array}{rl}
F'(x) & =f(h(x))\cdot h'(x)-f(g(x))\cdot g'(x)\\[0.25cm] & =\sin(x^2)\cdot (2x)-\sin(x)\cdot 1 =2x\cdot\sin(x^2)-\sin x.
\end{array}
$$