---
title: "Problemas de funciones"
author: ""
date: ""
output:
  pdf_document: default
              
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#reticulate::use_python("/Users/juangabriel/anaconda3/bin/python")
#reticulate::py_install("sympy")
```


1. Di a qué función corresponde la gráfica de la funciones siguientes:
    a)
```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-3
xmax=3
ymin=-3
ymax=3
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=6
quantsy=6
f = function(x){x}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-7*tolx,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
```
    b)
```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-2
xmax=2
ymin=-4
ymax=4
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=4
quantsy=8
f = function(x){x^2}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-7*tolx,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
```

    c)
```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-2
xmax=2
ymin=-8
ymax=8
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=4
quantsy=16
f = function(x){x^3}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-7*tolx,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
```


2. Di a qué función corresponde la gráfica de la funciones siguientes:

    a)
```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-3
xmax=5
ymin=-1
ymax=15
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=8
quantsy=8
f = function(x){exp(-x)}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-15*tolx,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,0.1+ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
```
    b) 
```{r,echo=FALSE,fig.align='center',fig.height=6,warning=FALSE}
xmin=-1
xmax=9
ymin=-2
ymax=4
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=10
quantsy=6
f = function(x){log(x)}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-15*tolx,"x")
text(toly,ymax+toly,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(2.5*tolx,ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
```
    c)
```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-3
xmax=3
ymin=-3
ymax=3
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=6
quantsy=6
f = function(x){1/x}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-7*tolx,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
```

3. Di a qué función corresponde la gráfica de la funciones siguientes:
    a) 
```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-5
xmax=5
ymin=-1
ymax=1
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=10
quantsy=4
f = function(x){sin(x)}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-toly,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(4*tolx,ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
```
    b) 
```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-5
xmax=5
ymin=-1
ymax=1
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=10
quantsy=4
f = function(x){cos(x)}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-toly,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(4*tolx,ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
```
    c)
```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-5
xmax=5
ymin=-5
ymax=5
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=10
quantsy=5
f = function(x){tan(x)}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-tolx,-7*tolx,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(4*tolx,ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
```