---
title: "Problemas de derivabilidad de funciones. Crecimiento, decrecimiento y regla de l'Hôpital"
author: ""
date: ""
geometry: "left=1.5cm,right=1.5cm,top=1.25cm,bottom=1.25cm"
output:
  pdf_document: default
  html_document: default
---



1. Dar los extremos relativos y los intervalos de crecimiento y decrecimiento de las funciones siguientes:
    a) $f(x)=x^2-3x+5$,
    a) $h(x)=x^3-3x-4$,
    a) $k(x)=x^4+2x^2-4$.

## Solución

a) Para hallar los extremos de $f(x)=x^2-3x+5$, primero tenemos que derivar e igualar la derivada a cero:
$$
f'(x)=2x-3=0,\ \Rightarrow x=\frac{3}{2}.
$$
Miremos los intervalos de crecimiento y decrecimiento a partir de la tabla siguiente:
<div class="center">
|$x$| $-\infty$| |$\frac{3}{2}$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|
|$f'$| |$-$| |$+$| |
|$f$| |$\searrow$| |$\nearrow$| |
</div>
Para comprobar los signos de la tabla anterior, hemos de hacer lo siguiente:
* Signo de $y'$ en el intervalo $\left(-\infty,\frac{3}{2}\right)$. Consideremos un valor en dicho intervalo, por ejemplo $x=0$, el valor de $f'(0)$ vale $f'(0)=2\cdot 0-3=-3<0$.
* Signo de $y'$ en el intervalo $\left(\frac{3}{2},\infty\right)$. Consideremos un valor en dicho intervalo, por ejemplo $x=2$, el valor de $f'(2)$ vale $f'(2)=2\cdot 2-3=1>0$.\newline
La función $f(x)$ crece en el intervalo $\left(\frac{3}{2},\infty\right)$, decrece en el intervalo $\left(-\infty,\frac{3}{2}\right)$ y tiene un mínimo en el punto $\left(\frac{3}{2},\left(\frac{3}{2}\right)^2-3\cdot \frac{3}{2}+5\right)=(`r 3/2`,`r (3/2)^2-3*3/2+5`).$\newline

b) Hagamos lo mismo para la función $h(x)=x^3-3x-4$:
$$
h'(x)=3x^2-3=0,\ \Rightarrow x=\pm 1.
$$
Tabla:
<div class="center">
|$x$| $-\infty$| |$-1$| |$1$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|$h'$| |$+$| |$-$| |$+$| |
|$h$| |$\nearrow$| |$\searrow$| |$\nearrow$| |
</div>
Para comprobar los signos de la tabla anterior, hemos de hacer lo siguiente:
* Signo de $y'$ en el intervalo $\left(-\infty,-1\right)$. Consideremos un valor en dicho intervalo, por ejemplo $x=-2$, el valor de $h'(-2)$ vale $h'(-2)=3\cdot (-2)^2-3 = 9>0$.
* Signo de $y'$ en el intervalo $\left(-1,1\right)$. Consideremos un valor en dicho intervalo, por ejemplo $x=0$, el valor de $h'(0)$ vale $h'(0)=3\cdot (0)^2-3 = -3<0$.
* Signo de $y'$ en el intervalo $\left(1,\infty\right)$. Consideremos un valor en dicho intervalo, por ejemplo $x=2$, el valor de $h'(2)$ vale $h'(2)=3\cdot (2)^2-3 = 9>0$.
La función $h(x)$ crece en la región $(-\infty,-1)\cup (1,\infty)$, decrece en el intervalo $(-1,1)$, tiene un máximo en $(-1,`r -1+3-4`)$ y un mínimo en $(1,`r 1-3-4`)$.

c) Función $k(x)=x^4+2x^2-4$:
$$
k'(x)=4 x^3+4x=0,\ \Rightarrow 4x (x^2+1)=0,\ \Rightarrow x=0.
$$
Tabla:
<div class="center">
|$x$| $-\infty$| |$0$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|
|$k'$| |$-$| |$+$| |
|$k$| |$\searrow$| |$\nearrow$| |
</div>
La función $k(x)$ crece en el intervalo $\left(0,\infty\right)$, decrece en el intervalo $\left(-\infty,0\right)$ y tiene un mínimo en el punto $(0,-4).$\newpage


2. Dar los extremos relativos y los intervalos de crecimiento y decrecimiento de las funciones siguientes:
    a) $f(x)=x+\frac{1}{x}$ para $x\neq 0$,
    a) $h(x)=\sqrt{x}-2\sqrt{x+1}$ para $x>0$,
    a) $g(x)=\frac{x}{x^2+1}$ para $x\in\mathbb{R}$.


## Solución

a) Para hallar los extremos relativos de la función $f(x)=x+\frac{1}{x}$ para $x\neq 0$ hay que derivar e igualar a cero la función derivada:
$$
f'(x)=1-\frac{1}{x^2}=0,\ \Rightarrow x=\pm 1.
$$
Miremos los intervalos de crecimiento y decrecimiento a partir de la tabla siguiente:
<div class="center">
|$x$| $-\infty$| |$-1$| |$0$|  |$1$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|$f'$| |$+$| |$-$| |$-$| |$+$| |
|$f$| |$\nearrow$| |$\searrow$| |$\searrow$| |$\nearrow$| |
</div>
La función $f(x)$ crece en la región $\left(-\infty,-1\right)\cup (1,\infty)$, decrece en la región $\left(-1,0\right)\cup (0,1)$,  tiene un máximo en el punto $(-1,-2)$ y un mínimo en el punto $(1,2)$.

b) Estudio para la función $h(x)=\sqrt{x}-2\sqrt{x+1}$ para $x>0$. La derivada y los ceros de la misma son:
$$
h'(x)=\frac{1}{2\sqrt{x}}-\frac{1}{\sqrt{x+1}},\ \Rightarrow \sqrt{x+1}=2\sqrt{x},\ \Rightarrow x+1=4 x,\ \Rightarrow x=\frac{1}{3}.
$$
Como hemos elevado al cuadrado, tenemos que comprobar que la solución hallada es efectivamente una solución de $h'(x)=0$:
$$
h'\left(\frac{1}{3}\right)=\frac{1}{2\sqrt{\frac{1}{3}}}-\frac{1}{\sqrt{\frac{1}{3}+1}}=\frac{\sqrt{3}}{2}-\frac{1}{\sqrt{\frac{4}{3}}}=\frac{\sqrt{3}}{2}-\frac{\sqrt{3}}{2}=0.
$$
Miremos los intervalos de crecimiento y decrecimiento a partir de la tabla siguiente:
<div class="center">
|$x$| $0$| |$\frac{1}{3}$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|
|$h'$| |$+$| |$-$| |
|$h$| |$\nearrow$| |$\searrow$| |
</div>
La función $h(x)$ crece en el intervalo $\left(0,\frac{1}{3}\right)$, decrece en el intervalo $\left(\frac{1}{3},\infty\right)$ y tiene un máximo en el punto $\left(\frac{1}{3},\sqrt{\frac{1}{3}}-2\sqrt{\frac{1}{3}+1}\right)=\left(\frac{1}{3},-\sqrt{3}\right)$.

c) Estudio para la función $g(x)=\frac{x}{x^2+1}$. La derivada y los ceros de la misma son:
$$
g'(x)=\frac{x^2+1-2x\cdot x}{(x^2+1)^2}=\frac{-x^2+1}{(x^2+1)^2}=0,\ \Rightarrow x=\pm 1.
$$
Miremos los intervalos de crecimiento y decrecimiento a partir de la tabla siguiente:
<div class="center">
|$x$| $-\infty$| |$-1$| |$1$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|$g'$| |$-$| |$+$| |$-$| |
|$g$| |$\searrow$| |$\nearrow$| |$\searrow$| |
</div>
La función $g(x)$ crece en el intervalo $(-1,1)$, decrece en la región $(-\infty,-1)\cup (1,\infty)$, tiene un mínimo en el punto $\left(-1,-\frac{1}{2}\right)$ y un máximo en el punto $\left(1,\frac{1}{2}\right)$.


\newpage

3. Usando la regla de L'Hôpital calcular los límites siguientes:
    a) $\displaystyle\lim_{x\to 0}\frac{\mathrm{e}^x+\mathrm{e}^{-x}-2}{1-\cos x}$,
    a) $\displaystyle\lim_{x\to 0}\frac{x^2-\sin^2 x}{x^4}$,
    a) $\displaystyle\lim_{x\to \infty}\frac{x^n}{\mathrm{e}^x}$, con $n$ valor entero, $n\geq 1$,
    a) $\displaystyle\lim_{x\to\frac{\pi}{2}^-}(\sec x-\tan x)$.


## Solución

a) El valor del límite será:
$$
\lim_{x\to 0}\frac{\mathrm{e}^x+\mathrm{e}^{-x}-2}{1-\cos x}=\lim_{x\to 0}\frac{\mathrm{e}^x-\mathrm{e}^{-x}}{\sin x}=\lim_{x\to 0}\frac{\mathrm{e}^x+\mathrm{e}^{-x}}{\cos x}=\frac{2}{1}=2.
$$

b) El valor del límite será:
$$
\begin{array}{rl}
\displaystyle\lim_{x\to 0}\frac{x^2-\sin^2 x}{x^4} &\displaystyle  =\lim_{x\to 0}\frac{2x-2 \sin x\cos x}{4 x^3}=\lim_{x\to 0}\frac{2-2 (\cos^2 x-\sin^2 x)}{12 x^2}=\lim_{x\to 0}\frac{-4 (-\cos x\sin x-\sin x\cos x)}{24 x}\\[0.25cm]
& \displaystyle = \lim_{x\to 0}\frac{8 \cos x\sin x}{24 x}=\lim_{x\to 0}\frac{-8 (\sin^2 x-\cos^2 x)}{24}=\frac{8}{24}=\frac{1}{3}.
\end{array}
$$

c) El valor del límite será:
$$
\lim_{x\to \infty}\frac{x^n}{\mathrm{e}^x} =\lim_{x\to \infty}\frac{n\cdot x^{n-1}}{\mathrm{e}^x}=\cdots = \lim_{x\to \infty}\frac{n!}{\mathrm{e}^x}=0.
$$

d) El valor del límite será:
$$
\lim_{x\to\frac{\pi}{2}^-}(\sec x-\tan x)=\lim_{x\to\frac{\pi}{2}^-}\frac{1-\sin x}{\cos x}=\lim_{x\to\frac{\pi}{2}^-}\frac{-\cos x}{-\sin x}=0.
$$