---
title: "Problemas de estudio de derivabilidad de funciones"
author: ""
date: ""
output:
  pdf_document: default
              
  html_document: default
---

1. Usando la definición, calcular la derivada de la función $\frac{1}{\sqrt{x}}$ para $x>0$ en un valor $x_0>0$.\newline\newline
**Solución:**\newline
Usando la definición, la derivada de la función $\frac{1}{\sqrt{x}}$ en $x_0>0$ será:
$$
\begin{array}{rl}
f'(x_0) & \displaystyle =\lim_{x\to x_0}\frac{f(x)-f(x_0)}{x-x_0}=\lim_{x\to x_0}\frac{\frac{1}{\sqrt{x}}-\frac{1}{\sqrt{x_0}}}{x-x_0}=\lim_{x\to x_0}\frac{\sqrt{x_0}-\sqrt{x}}{\sqrt{x\cdot x_0}\cdot (x-x_0)}\cdot \frac{\sqrt{x_0}+\sqrt{x}}{\sqrt{x_0}+\sqrt{x}} \\ & \displaystyle = \lim_{x\to x_0}\frac{x_0-x}{\sqrt{x\cdot x_0}\cdot (x-x_0)\cdot (\sqrt{x_0}+\sqrt{x})}=-\lim_{x\to x_0}\frac{1}{\sqrt{x\cdot x_0}\cdot (\sqrt{x_0}+\sqrt{x})}=-\frac{1}{2x_0\cdot \sqrt{x_0}}\\ & \displaystyle =-\frac{1}{x_0^{\frac{3}{2}}}.
\end{array}
$$
\newpage
1. Demostrar que la función $f(x)=\sqrt[5]{x}$ no es derivable en $x=0$.
\newline\newline
**Solución:**\newline
Intentemos calcular la derivada en $x=0$:
$$
f'(0)=\lim_{x\to 0}\frac{f(x)-f(0)}{x}=\lim_{x\to 0}\frac{\sqrt[5]{x}}{x}=\lim_{x\to 0} \frac{1}{x^{\frac{4}{5}}}=\frac{1}{0}=\infty!
$$
\newpage
1. Sea la función siguiente: 
$$
f(x)=\begin{cases}
x^2, & \mbox{ si $x$ es racional},\\
0, & \mbox{ si $x$ es irracional.}
\end{cases}
$$
Demostrar que $f(x)$ es derivable en $x=0$.
\newline\newline
**Solución:**\newline
Intentemos hallar la derivada en $x=0$:
$$
f'(0)=\lim_{x\to 0}\frac{f(x)-f(0)}{x}=\lim_{x\to 0}\frac{f(x)}{x}=0.
$$
Veamos que el límite $\displaystyle \lim_{x\to 0}\frac{f(x)}{x}=0$. Hay que ver que para todo valor $\epsilon >0$, existe un valor $\delta >0$ tal que si $|x|<\delta$ entonces $\left|\frac{f(x)}{x}\right|<\epsilon$.
\newline
Consideremos $\delta = \epsilon$. Entonces, si $|x|<\delta=\epsilon$, tendremos que $\left|\frac{f(x)}{x}\right|$ valdrá $\left|\frac{x^2}{x}\right|=|x|$, si $x$ es racional o $\left|\frac{0}{x}\right|=0$, si $x$ es irracional. En cualquiera de los dos casos, $\left|\frac{f(x)}{x}\right|< \epsilon$, tal como queríamos demostrar.
\newpage
1. Hallar los valores de $x$ en donde la siguiente función es derivable: $f(x)=|x|+|x+1|$ y hallar la derivada correspondiente.\newline\newline
**Solución**\newline
Escribamos la función anterior a trozos:
$$
f(x)=\begin{cases}
-x-(x+1)=-2x-1, & \mbox{si }x < -1,\\
-x+(x+1)=1, & \mbox{si }-1\leq x <0, \\
x+(x+1) =2x+1, & \mbox{si }x\geq 0.
\end{cases}
$$
Se puede verificar que dicha función es continua. Los únicos valores donde se tiene que estudiar la derivabilidad es en los puntos donde $f$ cambia de expresión que son los puntos $x=-1$ y $x=0$.\newline
Veamos si es derivable en el punto $x=-1$, o si existe el límite:
$$
\lim_{x\to -1}\frac{f(x)-f(-1)}{x+1}=\lim_{x\to -1}\frac{f(x)-1}{x+1}.
$$
Si hacemos el límite anterior por la izquierda o para valores $x<-1$, obtenemos:
$$
\lim_{x\to -1^-}\frac{f(x)-1}{x+1}=\lim_{x\to -1}\frac{-2x-1-1}{x+1}=\lim_{x\to -1}\frac{-2(x+1)}{x+1}=-2.
$$
Si hacemos el límite por la derecha o para valores $x>-1$, obtenemos:
$$
\lim_{x\to -1^+}\frac{f(x)-1}{x+1}=\lim_{x\to -1}\frac{1-1}{x+1}=0.
$$
Como los dos límites anteriores no coinciden, concluimos que $f$ no es derivable en $x=-1$.\newline
Para $x=0$, hacemos una cosa parecida:
$$
\lim_{x\to 0}\frac{f(x)-f(0)}{x}=\lim_{x\to 0}\frac{f(x)-1}{x}.
$$
Si hacemos el límite anterior por la izquierda o para valores $x<0$, obtenemos:
$$
\lim_{x\to 0^-}\frac{f(x)-1}{x} = \lim_{x\to 0^-}\frac{1-1}{x}=0.
$$
Si lo hacemos por la derecha o para valores $x>0$, obtenemos:
$$
\lim_{x\to 0^+}\frac{f(x)-1}{x} = \lim_{x\to 0^+}\frac{2x+1-1}{x}=\lim_{x\to 0^+}\frac{2x}{x}=2.
$$
Como los dos límites anteriores no coinciden, concluimos que $f$ no es derivable en $x=0$.
\newpage
1. Sea $f(x)$ una función derivable en un punto $x_0$. Demostrar que:
$$
f'(x_0)=\lim_{n\to\infty} \left( n\cdot\left(f(x_0+\frac{1}{n})-f(x_0)\right)\right).
$$
Demostrar que el recíproco es falso, es decir, dar un ejemplo de una función y un valor $x_0$ tal que exista el límite anterior pero la función no sea derivable en $x_0$. \newline
Indicación: considerar la función $f(x)=x\cdot \sin\left(\frac{\pi}{x}\right)$ si $x\neq 0$ y $f(0)=0$. Ver que el límite anterior
para $x_0=0$ existe pero $f(x)$ no es derivable en $x_0=0$.
\newline\newline
**Solución**\newline
Como $f$ es derivable en $x_0$, tenemos que existe el límite siguiente $\displaystyle f'(x_0)=\lim_{x\to x_0}\frac{f(x)-f(x_0)}{x-x_0}$. En particular se verifica que si $(x_n)_n$ es una sucesión de valores reales con límite $x_0$ ($\displaystyle\lim_{x\to x_0}x_n =x_0$), entonces existe el límite $\displaystyle f'(x_0)=\lim_{n\to \infty}\frac{f(x_n)-f(x_0)}{x_n-x_0}$ y vale $f'(x_0)$. Consideremos la sucesión siguiente $x_n =x_0+\frac{1}{n}$. Aplicando el resultado anterior a dicha sucesión, sale el resultado pedido.\newline
Para ver que el recíproco es falso, tal como dice la indicación, consideremos la función $f(x)=x\cdot \sin\left(\frac{\pi}{x}\right)$ si $x\neq 0$ y $f(0)=0$. Dicha función no es derivable en $x=0$ ya que el límite siguiente:
$$
\lim_{x\to 0}\frac{f(x)-f(0)}{x}=\lim_{x\to 0}\frac{x\cdot \sin\left(\frac{\pi}{x}\right)}{x}=\lim_{x\to 0}\sin\left(\frac{\pi}{x}\right),
$$
no existe ya que si consideramos la sucesiones siguientes $x_n = \frac{1}{n}$ e $y_n =\frac{1}{\frac{1}{2}+2n}$, las dos tienden a cero pero:
$$
\lim_{n\to \infty}\sin\left(\frac{\pi}{x_n}\right)=\lim_{n\to \infty}\sin (n\pi)=0,\quad \lim_{n\to \infty}\sin\left(\frac{\pi}{y_n}\right)=\lim_{n\to \infty}\sin \left(\frac{\pi}{2}+2n\pi\right)=1.
$$
En cambio, el límite 
$$
\lim_{n\to\infty} \left( n\cdot\left(f\left(\frac{1}{n}\right)-f(0)\right)\right)=\lim_{n\to\infty} \left( n\cdot f\left(\frac{1}{n}\right)\right)=\lim_{n\to\infty} \left( n\cdot \sin(\pi n)\right)=0,
$$
existe y vale $0$.
\newpage
1. Calcular la derivada de las funciones siguientes:
    a) $f(x)=\frac{x+1}{x^2+1}$.
    a) $f(x)=\tan (x^3+x^2+x-1)$.
    a) $f(x)=x^x$, para $x>0$. Indicación: considerar $g(x)=\ln f(x)$. Derivar la función $g(x)$ y a partir de la derivada de $g(x)$, hallar la derivada de la función $f(x)$.
\newline\newline
**Solución**\newline
Las funciones derivadas son las siguientes:\newline
Para $f(x)=\frac{x+1}{x^2+1}$, $f'(x)=\frac{1\cdot (x^2+1)-(x+1)\cdot 2x}{(x^2+1)^2}=\frac{-x^2-2x+1}{(x^2+1)^2}.$\newline
Para $f(x)=\tan (x^3+x^2+x-1)$, $f'(x)=\frac{1}{\cos^2 (x^3+x^2+x-1)}\cdot (3x^2+2x+1)=\frac{3x^2+2x+1}{\cos^2 (x^3+x^2+x-1)}.$\newline
Para $f(x)=x^x$, sea $g(x)=\ln f(x)=\ln x^x = x\cdot \ln x$. La derivada de la función $g(x)$ será, pon un lado, aplicando la derivada de la función logaritmo, $g'(x)=\frac{f'(x)}{f(x)}$ y, por otro, aplicando la regla del producto será: $g'(x)=\ln x+x\cdot \frac{1}{x}=\ln x+1$. Por tanto 
$$
\frac{f'(x)}{f(x)}=\ln x+1,\ \Rightarrow f'(x)=f(x)\cdot (\ln x+1)=x^x\cdot (\ln x+1).
$$
\newpage
1. Consideremos la función $f(x)=\frac{a}{a+x}$, donde $a$ es un valor real. Hallar la derivada $n$-ésima de $f$ en un valor $x_0\neq -a$.\newline\newline
**Solución**\newline
Hagamos las tres primeras derivadas:
$$
f'(x)=-\frac{a}{(a+x)^2},\quad f''(x)=\frac{2 a}{(a+x)^3},\quad f'''(x)=-\frac{6 a}{(a+x)^4},\ldots
$$
Parece que la expresión de la derivada $n$-ésima es:
$$
f^{(n)}(x)=(-1)^n\frac{n! a}{(a+x)^{n+1}}.
$$
Dejamos al lector que lo demuestre como ejercicio por inducción.
\newpage
1. Consideremos la función $f(x)=\frac{x^2-1}{x^2+1}$. Hallar la recta tangente de la curva $y=f(x)$ en el punto $(x_0=0,y_0=f(x_0)=-1)$.
\newline\newline
**Solución**\newline
La ecuación de la recta tangente en un punto $(x_0,f(x_0))$ a la curva $y=f(x)$ es la siguiente:
$$
y=f(x_0)+f'(x_0)\cdot (x-x_0).
$$
En nuestro caso, $x_0=0$, $f(x_0)=-1$ y
$$
f'(x)=\frac{2x (x^2+1)-2x (x^2-1)}{(x^2+1)^2}=\frac{4x}{(x^2+1)^2}.
$$
Por tanto $f'(x_0)=f'(0)=0$. La ecuación de la recta tangente pedida será, pues:
$y=-1.$ Se trataría de una recta horizontal.
\newpage
1. Diremos que una función $f:\mathbb{R}\longrightarrow \mathbb{R}$ es par si para todo valor de $x\in\mathbb{R}$, $f(x)=f(-x)$ y diremos que es impar si para todo valor $x\in\mathbb{R}$, $f(x)=-f(-x)$. Demostrar que la función derivada de toda función par es impar y viceversa, que la función derivada de toda función impar es par.\newline\newline
**Solución**\newline
Si la función es par, tendremos que para todo valor $x$, $f(x)=f(-x)$. Derivando la expresión anterior y aplicando la regla de la cadena obtenemos $f'(x)=-f'(-x)$ concluyendo que la función derivada es impar. Dejamos como ejercicio demostrar que la derivada de toda función impar es par.
\newpage
1. Sea $h(x)$ la función de Heaviside: $h(x)=1$, para $x\geq 0$ y $h(x)=0$, para $x<0$. Demostrar que no existe ninguna función $f:\mathbb{R}\longrightarrow\mathbb{R}$ tal que $f'(x)=h(x)$, para todo $x\in\mathbb{R}$. \newline\newline
**Solución**\newline
Supongamos que existe una función $f(x)$ tal que $f'(x)=h(x)$.\newline
Como $f'(x)=h(x)=1$ para $x>0$, tendremos que $f(x)=x+C$ donde $C$ es una constante.\newline
De la misma manera como $f'(x)=h(x)=0$ para $x<0$, tendremos que $f(x)=D$ donde $D$ es constante.
La función $f$ al ser derivable en todos los puntos, debe ser continua. En particular será continua en $x=0$:
$$
\lim_{x\to 0^-} f(x)=\lim_{x\to 0^+} f(x).\ \Rightarrow \lim_{x\to 0^-} x+C =C=\lim_{x\to 0^+} D =D.
$$
El valor de $f(x)$ será pues $f(x)=C$ si $x<0$ y $f(x)=x+C$ si $x\geq 0$. Veamos que dicha función no es derivable en $x=0$:
$$
\lim_{x\to 0^-}\frac{f(x)-f(0)}{x}=\lim_{x\to 0^-}\frac{C-C}{x}=0,
$$
pero
$$
\lim_{x\to 0^+}\frac{f(x)-f(0)}{x}=\lim_{x\to 0^+}\frac{C+x-C}{x}=\lim_{x\to 0^+}\frac{x}{x}=1.
$$
Al no coincidir los límites anteriores, vemos que $f$ no es derivable en $x=0$ llegando a una contradicción ya que $f$, como hemos indicado antes, debería ser derivable en todos los puntos.



