---
title: "Gráficas de funciones conocidas"
author: "Juan Gabriel Gomila, Arnau Mir y Llorenç Valverde"
date: ''
output: 
  ioslides_presentation: 
    css: Mery_style.css
    fig_caption: yes
    keep_md: yes
    logo: Images/calculus.gif
    widescreen: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#reticulate::use_python("/Users/juangabriel/anaconda3/bin/python")
#reticulate::py_install("sympy")
```

## Funciones polinómicas

```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-2
xmax=5
ymin=-7
ymax=15
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=7
quantsy=11
f = function(x){x^3-5*x^2+12}
g = function(x){x^4/10-7*x^3/10+x^2-2}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-15*tolx,"x")
text(toly/2,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,0.1+ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
lines(x,g(x),col="blue")
text(4,9,expression(paste("y=",x^3 - 5%.%x^2 + 12)),col="red")
text(-1.1,14,expression(paste("y=",frac(1,10)%.%x^4 - frac(7,10)%.%x^3 + x^2 - 2)),col="blue")
```


## Funciones exponenciales

```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-5
xmax=5
ymin=-1
ymax=15
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=10
quantsy=8
f = function(x){exp(x)}
g = function(x){exp(x/2)}
h = function(x){exp(-x)}
k = function(x){exp(-x/2)}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-15*tolx,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,0.1+ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
lines(x,g(x),col="blue")
lines(x,h(x),col="green")
lines(x,k(x),col="orange")
text(3,13,expression(paste("y=",e^x)),col="red")
text(4.5,7,expression(paste("y=",e^frac(x,2))),col="blue")
text(-2,13,expression(paste("y=",e^-x)),col="green")
text(-3.8,9,expression(paste("y=",e^-frac(x,2))),col="orange")
```

## Funciones trigonométricas

```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-5
xmax=5
ymin=-1
ymax=1
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=10
quantsy=4
f = function(x){sin(x)}
g = function(x){cos(x)}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-15*tolx,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
lines(x,g(x),col="blue")
text(3,0.75,expression(paste("y=",sin(x))),col="red")
text(-1.5,0.75,expression(paste("y=",cos(x))),col="blue")
```

## Funciones trigonométricas

```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-5
xmax=5
ymin=-10
ymax=10
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=10
quantsy=10
f = function(x){1/sin(x)}
g = function(x){1/cos(x)}
h = function(x){tan(x)}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-15*tolx,"x")
text(toly/2+0.2,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,0.1+ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
lines(x,g(x),col="blue")
lines(x,h(x),col="green")
text(3.75,7,expression(paste("y=",frac(1,sin(x)))),col="red")
text(2.25,7,expression(paste("y=",frac(1,cos(x)))),col="blue")
text(-2.3,7,expression(paste("y=",tan(x))),col="green")
text(-4,10,expression(paste("x=",frac(-5%.%pi,2))),col="green")
text(-2.5,10,expression(paste("x=",frac(-3%.%pi,2))),col="red")
text(-1,10,expression(paste("x=",frac(-pi,2))),col="green")
text(2,10,expression(paste("x=",frac(pi,2))),col="green")
text(3.65,10,expression(paste("x=",frac(3%.%pi,2))),col="red")
```

## Funciones trigonométricas

```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-1
xmax=1
ymin=-2
ymax=4
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=2
quantsy=6
f = function(x){asin(x)}
g = function(x){acos(x)}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-15*tolx,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,0.1+ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
lines(x,g(x),col="blue")
text(-0.75,-1.5,expression(paste("y=",sin^-1,(x))),col="red")
text(-0.75,3,expression(paste("y=",cos^-1,(x))),col="blue")
```

## Funciones trigonométricas

```{r,echo=FALSE,fig.align='center',fig.height=6}
xmin=-10
xmax=10
ymin=-2
ymax=2
tolx=0.01*(xmax-xmin)
toly=0.05*(ymax-ymin)
quantsx=10
quantsy=4
f = function(x){atan(x)}
plot(c(xmin-tolx,xmax+tolx,xmin-tolx,xmax+tolx),c(ymin-toly,ymin-toly,ymax+toly,ymax+toly),type="n",xlab="",ylab="",xaxt="n",yaxt="n",axes=FALSE)
x=seq(from=xmin,to=xmax,by=0.01)
#points(x,f(x),type="l")
lines(c(0,0),c(ymin,ymax))
lines(c(xmin,xmax),c(0,0))
text(xmax-3*tolx,-15*tolx,"x")
text(toly,ymax+toly/2,"y")
for (i in 0:(quantsx)){
  if(xmin+((xmax-xmin)/quantsx)*i != 0){
    lines(rep(xmin+((xmax-xmin)/quantsx)*i,2),c(-0.5*toly,+0.5*toly))
    text(xmin+((xmax-xmin)/quantsx)*i,-1*toly,xmin+((xmax-xmin)/quantsx)*i,cex=0.75)}
  }

for (i in 0:(quantsy)){
  lines(c(-tolx,tolx),ymin+rep(((ymax-ymin)/quantsy)*i,2))
 text(3.5*tolx,0.1+ymin+((ymax-ymin)/quantsy)*i,ymin+((ymax-ymin)/quantsy)*i,cex=0.75)
}
lines(x,f(x),col="red")
abline(h=pi/2,col="blue",lty=2)
abline(h=-pi/2,col="blue",lty=2)
text(-6.25,-1.25,expression(paste("y=",tan^-1,(x))),col="red")
text(9,-1.3,expression(paste("y=",-frac(pi,2))),col="blue")
text(9,1.85,expression(paste("y=",frac(pi,2))),col="blue")
```