---
title: "Problemas de límites de sucesiones"
author: ""
date: ""
output:
  pdf_document: default
              
  html_document: default
---

1. Calcula los límites siguientes:
    a) $\displaystyle\lim_{n\to\infty}\frac{3 n^5+4 n^4-n+7}{-n^5-n^4+2n^3+3n+4}.$
    a) $\displaystyle\lim_{n\to\infty}  2n-\sqrt{4n^2-n}.$
    
### Solución

a) El valor del límite vale:
$$
\lim_{n\to\infty}\frac{3 n^5+4 n^4-n+7}{-n^5-n^4+2n^3+3n+4} =\frac{3}{-1}=-3.
$$
a) Para calcular el límite, multiplicamos por el conjugado del numerador:
$$
\begin{array}{rl}
\displaystyle\lim_{n\to\infty}  (2n-\sqrt{4n^2-n})\cdot \frac{2n+\sqrt{4n^2-n}}{2n+\sqrt{4n^2-n}}  & \displaystyle =\lim_{n\to\infty}\frac{4n^2-(4n^2-n)}{2n+\sqrt{4n^2-n}}=\lim_{n\to\infty}\frac{n}{2n+\sqrt{4n^2-n}} \\[0.5cm]  & \displaystyle = \lim_{n\to\infty}\frac{\frac{n}{n}}{\frac{2n}{n}+\sqrt{4\frac{n^2}{n^2}-\frac{n}{n^2}}}=\frac{1}{2+\sqrt{4}}=\frac{1}{4}.
\end{array}
$$

\newpage

2. Calcula los límites siguientes:
    a) $\displaystyle\lim_{n\to\infty} \left(\frac{n^2}{n^2+n+1}\right)^{2n-1}.$
    a) $\displaystyle\lim_{n\to\infty} \left(\frac{\ln (n+1)}{\ln n}\right)^{\ln n}.$
 
### Solución

a) Como el límite de la base, $\frac{n^2}{n^2+n+1}$ tiende a $1$ y el exponente, $2n-1$, a infinito, el límite propuesto es tipo $\mathrm{e}$:
$$
\begin{array}{rl}
\displaystyle \lim_{n\to\infty} \left(\frac{n^2}{n^2+n+1}\right)^{2n-1} & \displaystyle =\mathrm{e}^{\lim_{n\to\infty}(2n-1)\left(\frac{n^2}{n^2+n+1}-1\right)}=\mathrm{e}^{\lim_{n\to\infty}(2n-1)\left(-\frac{(n+1)}{n^2+n+1}\right)} \\ & \displaystyle =\mathrm{e}^{\lim_{n\to\infty}\left(\frac{-2 n^2-n+1}{n^2+n+1}\right)} = \mathrm{e}^{-2}=\frac{1}{\mathrm{e}^2}.
\end{array}
$$
a) Como el límite de la base, $\frac{\ln (n+1)}{\ln n}$ tiende a $1$, ya que por el criterio de Stolz
$$
\begin{array}{rl}
\displaystyle\lim_{n\to\infty} \frac{\ln (n+1)}{\ln n}  & \displaystyle =\lim_{n\to\infty} \frac{\ln(n+2)-\ln(n+1)}{\ln (n+1)-\ln n}=\lim_{n\to\infty} \frac{\ln\left(\frac{n+2}{n+1}\right)}{\ln\left(\frac{n+1}{n} \right)} = \lim_{n\to\infty}\ln\left(\frac{n+2}{n+1}\right)^\frac{1}{\ln\left(\frac{n+1}{n} \right)}\\ & \displaystyle =\ln \lim_{n\to\infty}\left(\frac{n+2}{n+1}\right)^\frac{1}{\ln\left(\frac{n+1}{n} \right)} =\ln\left(\mathrm{e}^{\lim_{n\to\infty}\left(\frac{n+2}{n+1}-1\right)\cdot \frac{1}{\ln\left(\frac{n+1}{n} \right)}}\right)=\lim_{n\to \infty} \frac{1}{(n+1)\ln\left(\frac{n+1}{n}\right)} \\ & \displaystyle = \frac{1}{\lim_{n\to\infty}\ln\left(\frac{n+1}{n}\right)^{n+1} }=\frac{1}{\ln\left(\mathrm{e}^{\lim_{n\to \infty}(n+1)\cdot \left(\frac{n+1}{n}-1\right)}\right)} = \frac{1}{\ln\left(\mathrm{e}^{\lim_{n\to \infty} \left(\frac{n+1}{n}\right)}\right)}=\frac{1}{\ln\mathrm{e}^1}=1.
\end{array}
$$ 
y el exponente, $\ln n$, a infinito, el límite propuesto es tipo $\mathrm{e}$:
$$
\begin{array}{rl}
\displaystyle\lim_{n\to\infty} \left(\frac{\ln (n+1)}{\ln n}\right)^{\ln n}  & \displaystyle = \mathrm{e}^{\lim_{n\to\infty}\ln n\cdot \left(\frac{\ln (n+1)}{\ln n}-1\right)} = \mathrm{e}^{\lim_{n\to\infty}\ln n\cdot \left(\frac{\ln (n+1)-\ln n}{\ln n}\right)}=\mathrm{e}^{\lim_{n\to\infty} \left(\ln (n+1)-\ln n\right)} \\ & \displaystyle = \mathrm{e}^{\lim_{n\to\infty} \left(\ln\frac{(n+1)}{n}\right)} = \mathrm{e}^{\ln \lim_{n\to\infty} \left(\frac{n+1}{n}\right)}=\mathrm{e}^{\ln 1}=1.
\end{array}
$$

\newpage

3. Calcula el valor del límite de las sucesiones siguientes definidas de forma recurrente:
    a) $a_1 = \sqrt{2},$ $a_{n+1}=\sqrt{a_n}$.
    a) $x_1 = 3,$ $x_{n+1}=3-\frac{1}{x_n}$.
    
### Solución
a) Veamos que la sucesión $(a_n)_n$ es decreciente por inducción.

Para $n=1$, tenemos que 
$$
a_1 =\sqrt{2}\approx `r round(sqrt(2),4)` > a_2\approx `r round(sqrt(sqrt(2)),4)`.
$$
Supongamos ahora que $a_n > a_{n+1}$. Veamos que $a_{n+1}>  a_{n+2}$: si $a_n > a_{n+1}$, tendremos que $\sqrt{a_n} > \sqrt{a_{n+1}}$, lo que significa que $a_{n+1} > a_{n+2}$, tal como queríamos demostrar.

Veamos a continuación que $a_n >1$ por inducción. Para $n=1$ se cumple claramente. Supongamos ahora que $a_n >1$, entonces $\sqrt{a_n}>1$, lo que significa que $a_{n+1}>1$ tal como queríamos demostrar.

Como $a_n$ es una sucesión decreciente y acotada inferiormente, tiene límite. Sea $L=\displaystyle\lim_{n\to\infty}a_n$. Entonces $\displaystyle\lim_{n\to\infty}\sqrt{a_n} =\sqrt{L}$ y $L$ verificará que $L=\sqrt{L}$, de donde $L^2=L$. Entonces $L=0,1$. Como $a_n>1$, para todo $n$, $L$ necesariamente vale $1$: $L=1$.

b) Veamos primero que $x_n >2$ por inducción. El caso $n=1$ es claro.
Supongamos ahora que $x_n > 2$. Entonces:
$$
x_n > 2, \ \Rightarrow 0< \frac{1}{x_n}<\frac{1}{2},\ \Rightarrow -\frac{1}{2}<-\frac{1}{x_n}<0, \ \Rightarrow 2 < 3-\frac{1}{2}<3-\frac{1}{x_n}<3,\ \Rightarrow 2<a_{n+1},
$$
tal como queríamos demostrar.


A continuación veamos que la sucesión $(x_n)_n$ es decreciente por inducción.

Para $n=1$ tenemos que 
$$
x_1 =3 > x_2 =3-\frac{1}{3}=\frac{8}{3}.
$$
Supongamos ahora que $x_n > x_{n+1}$. Veamos que $x_{n+1}>  x_{n+2}$:  
$$
x_n > x_{n+1},\ \Rightarrow \frac{1}{x_n} < \frac{1}{x_{n+1}}(\mbox{ya que }x_n>2>0),\ \Rightarrow 3-\frac{1}{x_n} >3- \frac{1}{x_{n+1}},\ \Rightarrow x_{n+1}>  x_{n+2},
$$
tal como queríamos demostrar.

Como $x_n$ es una sucesión decreciente y acotada inferiormente por $2$, tiene límite. Sea $L=\displaystyle\lim_{n\to\infty} x_n$.
$L$ cumple:
$$
L=3-\frac{1}{L},\ \Rightarrow L^2=3L-1,\ \Rightarrow L^2-3L+1=0,\ \Rightarrow L=\frac{3\pm\sqrt{5}}{2}.
$$
Como $x_n >2$, el valor de $L$ es: $L=\frac{3+\sqrt{5}}{2}\approx `r round((3+sqrt(5))/2,4)`.$


\newpage

4. Calcula los límites siguientes:
    a) $\displaystyle \lim_{n\to\infty}\sqrt[n]{a^n+b^n}$, si $b>a>0$.
    a) $\displaystyle \lim_{n\to\infty}\sum_{k=1}^n \frac{1}{\sqrt[m]{n^m+k}}$, si $m\geq 2$ es un número natural.
    
    
### Solución
a) Si $b>a>0$, tenemos lo siguiente:
$$
b=\sqrt[n]{b^n}< \sqrt[n]{a^n+b^n} < \sqrt[n]{b^n+b^n}=b\sqrt[n]{2}.
$$
Como $\displaystyle\lim_{n\to\infty}\sqrt[n]{2}=\lim_{n\to\infty} 2^{\frac{1}{n}}=1$ ya que si $L=\lim_{n\to\infty} 2^{\frac{1}{n}}$, aplicando logaritmos, tenemos que:
$$
\ln L =\lim_{n\to\infty}\ln 2^{\frac{1}{n}}=\lim_{n\to\infty}\frac{1}{n}\cdot \ln 2=0,\ \Rightarrow L=1,
$$
aplicando el criterio del sandwitch, tenemos que $\displaystyle\lim_{n\to\infty} \sqrt[n]{a^n+b^n} =b.$

b) Observemos en primer lugar que para todo $k=1,\ldots,n$,
$$
\frac{1}{\sqrt[m]{n^m+n}} < \frac{1}{\sqrt[m]{n^m+k}} < \frac{1}{\sqrt[m]{n^m}}=\frac{1}{n}.
$$
Por tanto,
$$
\frac{n}{\sqrt[m]{n^m+n}} = \sum_{k=1}^n \frac{1}{\sqrt[m]{n^m+n}} <  \sum_{k=1}^n  \frac{1}{\sqrt[m]{n^m+k}} < \sum_{k=1}^n \frac{1}{n}=1.
$$
Como $\displaystyle\lim_{n\to\infty} \frac{n}{\sqrt[m]{n^m+n}}=1$, ya que:
$$
\lim_{n\to\infty} \frac{n}{\sqrt[m]{n^m+n}} =\lim_{n\to\infty} \frac{\frac{n}{n}}{\sqrt[m]{\frac{n^m}{n^m}+\frac{n}{n^m}}}=\frac{1}{\sqrt[m]{1+0}}=1,
$$
por el criterio del sandwich,  $\displaystyle \lim_{n\to\infty}\sum_{k=1}^n \frac{1}{\sqrt[m]{n^m+k}}=1.$


\newpage

5. Calcula los límites siguientes:
    a) $\displaystyle\lim_{n\to\infty} \frac{1^3+3^3+\cdots +(2n+1)^3}{n^4}.$
    a) $\displaystyle\lim_{n\to\infty} \left(\frac{1+3+\cdots +2n-1}{n+1}-\frac{(2n+1)}{2}\right).$

### Solución

a) Aplicamos el criterio de Stolz ya que la sucesión $(2n+1)^3$ es estrictamente creciente y no acotada:
$$
\lim_{n\to\infty} \frac{1^3+3^3+\cdots +(2n+1)^3}{n^4} = \lim_{n\to\infty}\frac{(2n+3)^3}{(n+1)^4-n^4}=\lim_{n\to\infty} \frac{8 n^3+36 n^2+54 n+27}{4 n^3+6 n^2+4 n+1}=\frac{8}{4}=2.
$$
a) En primer lugar, operamos:
$$
\begin{array}{rl}
\displaystyle\lim_{n\to\infty} \left(\frac{1+3+\cdots +2n-1}{n+1}-\frac{(2n+1)}{2}\right) & \displaystyle = \lim_{n\to\infty}\frac{2+6+\cdots +2(2n-1)-(n+1)(2n+1)}{2(n+1)}\\ & \displaystyle =\lim_{n\to\infty}\frac{2+6+\cdots +4n-2-(n+1)(2n+1)}{2(n+1)}.
\end{array}
$$
A continuación, aplicamos el criterio de Stolz ya que la sucesión $2(n+1)$ es estrictamente creciente y no acotada:
$$
\lim_{n\to\infty} \frac{4n+2-(n+2)(2n+3)+(n+1)(2n+1)}{2(n+2)-2(n+1)}=\lim_{n\to\infty}\frac{-3}{2}=-\frac{3}{2}.
$$