---
title: "Problemas de límites con `python`"
author: ""
date: ""
output:
  pdf_document: default
              
  html_document: default
---

1. Calcula el límite siguiente en `python`:
$$
\lim_{x \rightarrow 0}\dfrac{\sqrt{1+2x} - \sqrt{1+3x}}{x+2x^2}.
$$
1. Demuestra usando `python` que no existe el $\displaystyle\lim_{x \rightarrow 0}  \cos \dfrac{1}{x}$ y que $\displaystyle\lim_{x \rightarrow 0} x \cos \dfrac{1}{x}=0$.
1. Calcula los límites siguientes usando `python`:
    a) $\displaystyle\lim_{x \rightarrow 1} \dfrac{\sqrt{x} -1}{x-1}.$
    a) $\displaystyle\lim_{x \rightarrow a} \dfrac{x^2-(a+1)x+a}{x^3-a^3},$ para $a=2$.
    a) $\displaystyle\lim_{x \rightarrow 0}\left(\dfrac{1-x}{1+x}\right)^{\dfrac{1}{x}}.$
    a) $\displaystyle{\lim_{x \rightarrow 0}\dfrac{1}{x} \log \sqrt{\dfrac{1+x}{1-x}}}.$
1. Calcula los límites siguientes usando `python`:
    a) $\displaystyle\lim_{x \rightarrow 0} \dfrac{\sin 2x}{3x -5x^3}.$
    a) $\displaystyle\lim_{x \rightarrow 0}\dfrac{\sqrt[3]{x^3+2x^4}}{\log (1+2x)}.$
    a) $\displaystyle\lim_{x \rightarrow 0}\dfrac{(x+1)^n-1}{nx},$ para $n\in\mathbb{N}$.
    a) $\displaystyle{\lim_{x \rightarrow 0} \dfrac{\sqrt[n]{x+1}-1}{x}}.$
    a) $\displaystyle \lim_{x \rightarrow 1}\dfrac{\tan(x^2-1)}{x-1}.$
    a) $\displaystyle{\lim_{x \rightarrow 0}\dfrac{a^x-1}{x \log a}}.$
