---
title: "Problemas de límites con `python`"
author: ""
date: ""
output:
  pdf_document: default
              
  html_document: default
---

1. Calcula el límite siguiente en `python`:
$$
\lim_{x \rightarrow 0}\dfrac{\sqrt{1+2x} - \sqrt{1+3x}}{x+2x^2}.
$$

### Solución

```{python}
from sympy import limit, Symbol, sqrt
x = Symbol("x")
limit((sqrt(1+2*x)-sqrt(1+3*x))/(x+2*x**2), x, 0)
```



\newpage

2. Demuestra usando `python` que no existe el $\displaystyle\lim_{x \rightarrow 0}  \cos \dfrac{1}{x}$ y que $\displaystyle\lim_{x \rightarrow 0} x \cos \dfrac{1}{x}=0$.

### Solución


```{python}
from sympy import limit, Symbol, cos
x = Symbol("x")
limit(cos(1/x), x, 0)
limit(x*cos(1/x),x,0)
```

\newpage

3. Calcula los límites siguientes usando `python`:
    a) $\displaystyle\lim_{x \rightarrow 1} \dfrac{\sqrt{x} -1}{x-1}.$
    a) $\displaystyle\lim_{x \rightarrow a} \dfrac{x^2-(a+1)x+a}{x^3-a^3},$ para $a=2$.
    a) $\displaystyle\lim_{x \rightarrow 0}\left(\dfrac{1-x}{1+x}\right)^{\dfrac{1}{x}}.$
    a) $\displaystyle{\lim_{x \rightarrow 0}\dfrac{1}{x} \log \sqrt{\dfrac{1+x}{1-x}}}.$
    
### Solución

a) 
```{python}
from sympy import limit, Symbol, sqrt, log
x = Symbol("x")
limit((sqrt(x)-1)/(x-1), x, 0)
```

b) 
```{python}
a = 2
limit((x**2-(a+1)*x+a)/(x**3-a**3),x,a)
```

c) 
```{python}
limit(((1-x)/(1+x))**(1/x), x, 0)
```

d) 
```{python}
limit((1/x)*log(sqrt((1+x)/(1-x))), x, 0)
```

\newpage

4. Calcula los límites siguientes usando `python`:
    a) $\displaystyle\lim_{x \rightarrow 0} \dfrac{\sin 2x}{3x -5x^3}.$
    a) $\displaystyle\lim_{x \rightarrow 0}\dfrac{\sqrt[3]{x^3+2x^4}}{\log (1+2x)}.$
    a) $\displaystyle\lim_{x \rightarrow 0}\dfrac{(x+1)^n-1}{nx},$ para $n\in\mathbb{N}$.
    a) $\displaystyle{\lim_{x \rightarrow 0} \dfrac{\sqrt[n]{x+1}-1}{x}}.$
    a) $\displaystyle \lim_{x \rightarrow 1}\dfrac{\tan(x^2-1)}{x-1}.$
    a) $\displaystyle{\lim_{x \rightarrow 0}\dfrac{a^x-1}{x \log a}},$ con $a>0$.


### Solución

a) 
```{python}
from sympy import limit, Symbol, sin, log, tan
x = Symbol("x")
limit(sin(2*x)/(3*x-5*x**3), x, 0)
```

b) 
```{python}
limit((x**3+2*(x**4))**(1./3.)/log(1+2*x),x,0)
```

c) 
```{python}
n= Symbol("n")
limit(((x+1)**n-1)/(n*x),x,0)
```


d) 
```{python}
n= Symbol("n")
limit(((x+1)**(1/n)-1)/x,x,0)
```

e) 
```{python}
limit(tan(x**2-1)/(x-1),x,1)
```

f) 
```{python}
a = Symbol("a")
limit((a**x-1)/(x*log(a)),x,0)
```
