---
title: "Problemas de derivabilidad de funciones. Fórmula de Taylor"
author: ""
date: ""
output:
  pdf_document: default
              
  html_document: default
---

1. Usando inducción, demostrar la regla de Leibnitz para hallar la derivada $n$-ésima del producto de dos funciones:
$$
(f\cdot g)^{(n)}(x)=\sum_{k=0}^n \binom{n}{k} f^{(n-k)}(x)\cdot g^{(k)}(x).
$$

## Solución

Veamos primero que la fórmula anterior es cierta para $n=1$:
$$
(f\cdot g)'(x)=\sum_{k=0}^1 \binom{n}{k} f^{(n-k)}(x)\cdot g^{(k)}(x)=f'(x)\cdot g(x)+f(x)\cdot g'(x).
$$
Vemos que es la fórmula de derivada del producto. Por tanto, la expresión es cierta para $n=1$.

Suponemos ahora que la fórmula es cierta para $n$ y hemos de verla para $n+1$ que sería:
$$
(f\cdot g)^{(n+1)}(x)=\sum_{k=0}^{n+1} \binom{n+1}{k} f^{(n+1-k)}(x)\cdot g^{(k)}(x).
$$
Como sabemos por hipótesis de inducción que:
$$
(f\cdot g)^{(n)}(x)=\sum_{k=0}^n \binom{n}{k} f^{(n-k)}(x)\cdot g^{(k)}(x),
$$
derivando la expresión anterior, obtenemos:
$$
\begin{array}{rl}
(f\cdot g)^{(n+1)}(x) & \displaystyle =\sum_{k=0}^n \binom{n}{k} (f^{(n-k+1)}(x)\cdot g^{(k)}(x)+f^{(n-k)}(x)\cdot g^{(k+1)}(x)),\\
& =\displaystyle  \sum_{k=0}^n \binom{n}{k} f^{(n-k+1)}(x)\cdot g^{(k)}(x) +\sum_{k=0}^n \binom{n}{k} f^{(n-k)}(x)\cdot g^{(k+1)}(x)\\
& =\displaystyle f^{(n+1)}(x)+\sum_{k=1}^n \binom{n}{k} f^{(n-k+1)}(x)\cdot g^{(k)}(x)+\sum_{k=0}^{n-1} \binom{n}{k} f^{(n-k)}(x)\cdot g^{(k+1)}(x)+g^{(n+1)}(x) \\
& =\displaystyle f^{(n+1)}(x)+\sum_{k=1}^n \binom{n}{k} f^{(n-k+1)}(x)\cdot g^{(k)}(x)+\sum_{k=1}^{n} \binom{n}{k-1} f^{(n+1-k)}(x)\cdot g^{(k)}(x)+g^{(n+1)}(x) \\
& =\displaystyle f^{(n+1)}(x)+\sum_{k=1}^n \left(\binom{n}{k}+ \binom{n}{k-1}\right) f^{(n-k+1)}(x)\cdot g^{(k)}(x)+g^{(n+1)}(x) \\
& =\displaystyle f^{(n+1)}(x)+\sum_{k=1}^n \binom{n+1}{k} f^{(n-k+1)}(x)\cdot g^{(k)}(x)+g^{(n+1)}(x) =\sum_{k=0}^{n+1} \binom{n+1}{k} f^{(n-k+1)}(x)\cdot g^{(k)}(x),
\end{array}
$$
tal como queríamos demostrar.

\newpage

2. Si $x>0$, demostrar que:
$$
\left|(1+x)^\frac{1}{3}-\left(1+\frac{1}{3}x-\frac{1}{9}x^2\right)\right|\leq \frac{5}{81}x^3.
$$
Usar la desigualdad anterior para hallar aproximaciones de $\sqrt[3]{1.2}$ y de $\sqrt[3]{2}$.


## Solución

Consideremos la función $f(x)=(1+x)^\frac{1}{3}$. Vamos a hallar el polinomio de Taylor de grado 2 de $f(x)$ en $x_0=0$ , es decir, el desarrollo de MacLaurin de $f(x)$ hasta grado 2.

Calculemos las tres primeras derivadas de la función $f(x)$:
$$
f'(x)=\frac{1}{3}\cdot (1+x)^{-\frac{2}{3}},\ f''(x)=-\frac{2}{9}\cdot (1+x)^{-\frac{5}{3}},\ f'''(x)=\frac{10}{27}\cdot (1+x)^{-\frac{8}{3}}.
$$
Para $x_0=0$, el valor de las derivadas anteriores vale:
$$
f'(0)=\frac{1}{3},\ f''(0)=-\frac{2}{9},\ f'''(0)=\frac{10}{27}.
$$
El desarrollo de MacLaurin de $f(x)$ junto con la expresión del error será:
$$
f(x)=(1+x)^\frac{1}{3}=1+\frac{1}{3}x-\frac{1}{9}x^2+\frac{5}{81}\cdot (1+c)^{-\frac{8}{3}}\cdot x^3,
$$
con $c\in (0,x)$, ya que $x>0$.

Como $c\in (0,x)$, podemos decir que el error está en:
$$
\frac{5}{81}\cdot (1+x)^{-\frac{8}{3}}\cdot x^3 \leq \frac{5}{81}\cdot (1+c)^{-\frac{8}{3}}\cdot x^3 \leq \frac{5}{81}\cdot x^3.
$$
Es decir:
$$
0\leq \frac{5}{81}\cdot (1+x)^{-\frac{8}{3}}\cdot x^3 \leq (1+x)^\frac{1}{3}-\left(1+\frac{1}{3}x-\frac{1}{9}x^2\right) \leq \frac{5}{81}\cdot x^3.
$$
Como $(1+x)^\frac{1}{3}-\left(1+\frac{1}{3}x-\frac{1}{9}x^2\right)$ es positivo, podemos escribir que:
$$
\left|(1+x)^\frac{1}{3}-\left(1+\frac{1}{3}x-\frac{1}{9}x^2\right)\right|\leq \frac{5}{81}x^3,
$$
tal como queríamos demostrar.

Para hallar una aproximación de $\sqrt[3]{1.2}$, aplicamos la expresión anterior para $x=0.2$:
$$
\left|(1.2)^\frac{1}{3}-\left(1+\frac{1}{3}\cdot 0.2-\frac{1}{9}\cdot 0.2^2\right)\right|\leq \frac{5}{81}\cdot 0.2^3,\ \Rightarrow \left|(1.2)^\frac{1}{3}-`r round(1+0.2/3-0.2^2/9,4)`\right|\leq `r round((5/81)*0.2^3,4)`.
$$

Para hallar una aproximación de $\sqrt[3]{2}$, aplicamos la expresión anterior para $x=1$:
$$
\left|2^\frac{1}{3}-\left(1+\frac{1}{3}-\frac{1}{9}\right)\right|\leq \frac{5}{81},\ \Rightarrow \left|2^\frac{1}{3}-`r round(1+1/3-1/9,4)`\right|\leq `r round((5/81),4)`.
$$

\newpage

3. Si $x\in [0,1]$ y $n\in\mathbb{N}$, demostrar que:
$$
\left|\ln (x+1)-\left(x-\frac{x^2}{2}+\frac{x^3}{3}+\cdots +(-1)^{n-1}\frac{x^n}{n}\right)\right|<\frac{x^{n+1}}{n+1.}
$$
Usar la expresión anterior para calcular $\ln 1.5$ con un error menor que $0.001$.

\newpage

4. Sea $I=(a,b)$ un intervalo abierto y $c\in I$. Sean $f$ y $g$ dos funciones definidas en $I$ tal que las funciones derivadas $f^{(k)}$ y $g^{(k)}$ existen y son continuas en $I$, para $k=0,1,\ldots, n$. Supongamos que $f^{(k)}(c)=g^{(k)}(c)=0$ para $k=0,1,\ldots,n-1$ y $g^{(n)}\neq 0$. Demostrar que:
$$
\lim_{x\to c}\frac{f(x)}{g(x)}=\frac{f^{(n)}(c)}{g^{(n)}(c)}.
$$