---
title: "Problemas de derivabilidad de funciones. Teoremas de derivabilidad"
author: ""
date: ""
geometry: "left=2cm,right=2cm,top=2cm,bottom=2cm"
output:
  pdf_document: default
  html_document: default
---

1. Consideremos el polinomio de grado $4$, $p_4(x)=x^4-a^2 x^2+b$ donde $a$ y $b$ son valores reales. Demostrar que $p_4(x)$ tiene tres extremos relativos, dos mínimos y un máximo.
1. Demostrar que para todo valor $x,y\in\mathbb{R}$, $\cos x-\cos y|\leq |x-y|$.
1. Dar los extremos relativos y los intervalos de crecimiento y decrecimiento de las funciones siguientes:
    a) $f(x)=x^2-3x+5$,
    a) $h(x)=x^3-3x-4$,
    a) $k(x)=x^4+2x^2-4$.
1. Dar los extremos relativos y los intervalos de crecimiento y decrecimiento de las funciones siguientes:
    a) $f(x)=x+\frac{1}{x}$ para $x\neq 0$,
    a) $h(x)=\sqrt{x}-2\sqrt{x+1}$ para $x>0$,
    a) $g(x)=\frac{x}{x^2+1}$ para $x\in\mathbb{R}$.
1. Sean $a>b>0$ números reales y $n\in\mathbb{N}$ un entero positivo con $n\geq 2$. Demostrar que $a^{\frac{1}{n}}-b^{\frac{1}{n}}< (a-b)^{\frac{1}{n}}$.
Indicación: demostrar que la función $f(x)=x^{\frac{1}{n}}-(x-1)^{\frac{1}{n}}$ es decreciente para $x\geq 1$ y evaluarla en $x=1$ y $x=\frac{a}{b}$.
1. Sea $f:[0,2]\longrightarrow \mathbb{R}$, continua en $[0,2]$ y derivable en $(0,2)$. Supongamos que $f(0)=0,\ f(1)=f(2)=1$.
    a) Demostrar que existe un valor $c_1\in (0,1)$ tal que $f'(c_1)=1$.
    a) Demostrar que existe un valor $c_2\in (1,2)$ tal que $f'(c_2)=0$.
    a) Demostrar que existe un valor $c_3\in (0,2)$ tal que $f'(c_3)=\frac{1}{3}$.
1. Usando la regla de L'Hôpital calcular los límites siguientes:
    a) $\displaystyle\lim_{x\to 0}\frac{\mathrm{e}^x+\mathrm{e}^{-x}-2}{1-\cos x}$,
    a) $\displaystyle\lim_{x\to 0}\frac{x^2-\sin^2 x}{x^4}$,
    a) $\displaystyle\lim_{x\to \infty}\frac{x^n}{\mathrm{e}^x}$, con $n$ valor entero, $n\geq 1$,
    a) $\displaystyle\lim_{x\to\frac{\pi}{2}^-}(\sec x-\tan x)$.
1. Descomponer un número $a$ en dos sumandos $x$ e $y$ tal que el valor de $x^2+y^2$ sea mínimo.
1. Determinar las dimensiones que ha de tener un bote cilíndrico de 2 litros de capacidad para que se construya con la cantidad mínima de material.
1. De todos los rectángulos de igual perímetro, ¿cuál es el que tiene área mayor?