---
title: "Problemas de derivabilidad de funciones. Optimización"
author: ""
date: ""
geometry: "left=1.5cm,right=1.5cm,top=1.25cm,bottom=1.25cm"
output:
  pdf_document: default
  html_document: default
---


1. Descomponer un número $a$ en dos sumandos $x$ e $y$ tal que el valor de $x^2+y^2$ sea mínimo.

## Solución

Se tiene que verificar que $x+y=a$ y hay que minimizar la función $x^2+y^2$.

Escribiendo dicha función sólo en función de $x$, obtenemos $f(x)=x^2+(a-x)^2$.

Para hallar el mínimo, tenemos que derivar e igualar a cero:
$$
f'(x)=2x-2 (a-x)=0,\ \Rightarrow x=\frac{a}{2}.
$$
Los valores $x$ e $y$ pedidos son: $x=\frac{a}{2}$, $y=a-x=a-\frac{a}{2}=\frac{a}{2}$. 

Comprobemos que es un mínimo:
$$
f''(x)=2+2=4 >0.
$$


\newpage

2. Determinar las dimensiones que ha de tener un bote cilíndrico de 2 litros de capacidad para que se construya con la cantidad mínima de material.

## Solución

Sea $r$ el radio de la base del bote y $h$ la altura del mismo.
La superficie lateral del bote será $2\pi r h$ y la superficie de las dos tapas, $2\pi r^2$.
Por tanto, hay que minimizar la función $2\pi r h+2\pi r^2$.

Sabemos que la capacidad del bote vale $\pi r^2 h=\frac{2}{1000}$ ($2$ litros son $\frac{2}{1000}$ m${}^3$). Por tanto $h=\frac{2}{1000\pi r^2}$.

La función a minimizar será:
$$
f(r)=2\pi r \frac{2}{1000\pi r^2}+2\pi r^2 =\frac{4}{1000r}+2\pi r^2.
$$
Para hallar el mínimo, tenemos que derivar e igualar a cero:
$$
f'(r)=-\frac{4}{1000r^2}+4\pi r=0,\ \Rightarrow r^3=\frac{1}{1000\pi},\ \Rightarrow r=\sqrt[3]{\frac{1}{1000\pi}}\approx `r round((1/(1000*pi))^(1/3),3)`\ \mathrm{m.}
$$
El valor de $h$ será: $h=\frac{2}{1000\pi r^2}=\frac{2}{1000\pi \left(\frac{1}{1000\pi}\right)^{\frac{2}{3}}}=\frac{2}{\sqrt[3]{1000\pi}}\approx `r round(2/(1000*pi)^(1/3),3)`$ m.

Comprobemos que es un mínimo:
$$
f''(r)=\frac{8}{1000r^3}+4\pi >0.
$$
\newpage

3. De todos los rectángulos de igual perímetro, ¿cuál es el que tiene área mayor?

## Solución

Sean $a$ y $b$ las dimensiones del rectángulo y $P$ el perímetro. Nos dicen que $2a+2b=P$ o, si se quiere $a+b=\frac{P}{2}$.

La función a maximizar es el área $a\cdot b$. Si la escribimos en función de $a$, obtenemos:
$$
f(a)=a\cdot \left(\frac{P}{2}-a\right).
$$

Para hallar el máximo, tenemos que derivar e igualar a cero:
$$
f'(a)=\frac{P}{2}-a-a=0,\ \Rightarrow a=\frac{P}{4}.
$$
Las dimensiones del rectángulo serán: $a=\frac{P}{4}$ y $b=\frac{P}{2}-a=\frac{P}{2}-\frac{P}{4}=\frac{P}{4}$.

Comprobemos que es un máximo:
$$
f''(a)=-2 <0.
$$