---
title: "Problemas de derivabilidad de funciones. Teoremas de derivabilidad"
author: ""
date: ""
geometry: "left=1.5cm,right=1.5cm,top=1.25cm,bottom=1.25cm"
output:
  pdf_document: default
  html_document: default
---

1. Consideremos el polinomio de grado $4$, $p_4(x)=x^4-a^2 x^2+b$ donde $a$ y $b$ son valores reales. Demostrar que $p_4(x)$ tiene tres extremos relativos, dos mínimos y un máximo.



## Solución

Para hallar los extremos hallemos la derivada de $p_4(x)$ y calculemos los valores que la anulan:
$$
p_4'(x)=4 x^3-2 a^2 x=0,\ \Rightarrow 2x\cdot (2x^2-a^2)=0,\ \Rightarrow x=-\frac{|a|}{\sqrt{2}},0,\frac{|a|}{\sqrt{2}}.
$$
Para saber si son máximos o mínimos, miramos el signo de $p_4''(x)$:
$$
p_4''(x)=12 x^2-2 a^2.
$$
Para $x=-\frac{|a|}{\sqrt{2}}$, $p_4''\left(-\frac{|a|}{\sqrt{2}}\right)=12\cdot\frac{a^2}{2}-2 a^2=4 a^2>0.$ Se trataría de un mínimo.\newline
Para $x=0$, $p_4''(0)=-2 a^2< 0.$ Se trataría de un máximo.\newline
Para $x=\frac{|a|}{\sqrt{2}}$, $p_4''\left(\frac{|a|}{\sqrt{2}}\right)=12\cdot\frac{a^2}{2}-2 a^2=4 a^2>0.$ Se trataría de un mínimo.\newline
Por tanto, $p_4(x)$ tiene dos mínimos y un máximo.

\newpage

2. Demostrar que para todo valor $x,y\in\mathbb{R}$, $\cos x-\cos y|\leq |x-y|$.\newline\newline


## Solución

Sea $f(x)=\cos x$. Supongamos para fijar ideas que $x<y$. Como $f(x)$ es derivable y continua en $\mathbb{R}$, podemos aplicar el Teorema del Valor Medio a la función $f(x)$ en el intervalo $(x,y)$ y obtener:
$$
f(x)-f(y)=f'(c)\cdot (x-y),\ \Rightarrow \cos x-\cos y=-\sin c\cdot (x-y), \ \Rightarrow |\cos x-\cos y|=|\sin c|\cdot |x-y|\leq |x-y|,
$$
tal como queríamos ver.

\newpage

3. Dar los extremos relativos y los intervalos de crecimiento y decrecimiento de las funciones siguientes:
    a) $f(x)=x^2-3x+5$,
    a) $h(x)=x^3-3x-4$,
    a) $k(x)=x^4+2x^2-4$.

## Solución

a) Para hallar los extremos de $f(x)=x^2-3x+5$, primero tenemos que derivar e igualar la derivada a cero:
$$
f'(x)=2x-3=0,\ \Rightarrow x=\frac{3}{2}.
$$
Miremos los intervalos de crecimiento y decrecimiento a partir de la tabla siguiente:
<div class="center">
|$x$| $-\infty$| |$\frac{3}{2}$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|
|$f'$| |$-$| |$+$| |
|$f$| |$\searrow$| |$\nearrow$| |
</div>
Para comprobar los signos de la tabla anterior, hemos de hacer lo siguiente:
* Signo de $y'$ en el intervalo $\left(-\infty,\frac{3}{2}\right)$. Consideremos un valor en dicho intervalo, por ejemplo $x=0$, el valor de $f'(0)$ vale $f'(0)=2\cdot 0-3=-3<0$.
* Signo de $y'$ en el intervalo $\left(\frac{3}{2},\infty\right)$. Consideremos un valor en dicho intervalo, por ejemplo $x=2$, el valor de $f'(2)$ vale $f'(2)=2\cdot 2-3=1>0$.\newline
La función $f(x)$ crece en el intervalo $\left(\frac{3}{2},\infty\right)$, decrece en el intervalo $\left(-\infty,\frac{3}{2}\right)$ y tiene un mínimo en el punto $\left(\frac{3}{2},\left(\frac{3}{2}\right)^2-3\cdot \frac{3}{2}+5\right)=(`r 3/2`,`r (3/2)^2-3*3/2+5`).$\newline

b) Hagamos lo mismo para la función $h(x)=x^3-3x-4$:
$$
h'(x)=3x^2-3=0,\ \Rightarrow x=\pm 1.
$$
Tabla:
<div class="center">
|$x$| $-\infty$| |$-1$| |$1$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|$h'$| |$+$| |$-$| |$+$| |
|$h$| |$\nearrow$| |$\searrow$| |$\nearrow$| |
</div>
Para comprobar los signos de la tabla anterior, hemos de hacer lo siguiente:
* Signo de $y'$ en el intervalo $\left(-\infty,-1\right)$. Consideremos un valor en dicho intervalo, por ejemplo $x=-2$, el valor de $h'(-2)$ vale $h'(-2)=3\cdot (-2)^2-3 = 9>0$.
* Signo de $y'$ en el intervalo $\left(-1,1\right)$. Consideremos un valor en dicho intervalo, por ejemplo $x=0$, el valor de $h'(0)$ vale $h'(0)=3\cdot (0)^2-3 = -3<0$.
* Signo de $y'$ en el intervalo $\left(1,\infty\right)$. Consideremos un valor en dicho intervalo, por ejemplo $x=2$, el valor de $h'(2)$ vale $h'(2)=3\cdot (2)^2-3 = 9>0$.
La función $h(x)$ crece en la región $(-\infty,-1)\cup (1,\infty)$, decrece en el intervalo $(-1,1)$, tiene un máximo en $(-1,`r -1+3-4`)$ y un mínimo en $(1,`r 1-3-4`)$.

c) Función $k(x)=x^4+2x^2-4$:
$$
k'(x)=4 x^3+4x=0,\ \Rightarrow 4x (x^2+1)=0,\ \Rightarrow x=0.
$$
Tabla:
<div class="center">
|$x$| $-\infty$| |$0$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|
|$k'$| |$-$| |$+$| |
|$k$| |$\searrow$| |$\nearrow$| |
</div>
La función $k(x)$ crece en el intervalo $\left(0,\infty\right)$, decrece en el intervalo $\left(-\infty,0\right)$ y tiene un mínimo en el punto $(0,-4).$\newpage


4. Dar los extremos relativos y los intervalos de crecimiento y decrecimiento de las funciones siguientes:
    a) $f(x)=x+\frac{1}{x}$ para $x\neq 0$,
    a) $h(x)=\sqrt{x}-2\sqrt{x+1}$ para $x>0$,
    a) $g(x)=\frac{x}{x^2+1}$ para $x\in\mathbb{R}$.


## Solución

a) Para hallar los extremos relativos de la función $f(x)=x+\frac{1}{x}$ para $x\neq 0$ hay que derivar e igualar a cero la función derivada:
$$
f'(x)=1-\frac{1}{x^2}=0,\ \Rightarrow x=\pm 1.
$$
Miremos los intervalos de crecimiento y decrecimiento a partir de la tabla siguiente:
<div class="center">
|$x$| $-\infty$| |$-1$| |$0$|  |$1$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|$f'$| |$+$| |$-$| |$-$| |$+$| |
|$f$| |$\nearrow$| |$\searrow$| |$\searrow$| |$\nearrow$| |
</div>
La función $f(x)$ crece en la región $\left(-\infty,-1\right)\cup (1,\infty)$, decrece en la región $\left(-1,0\right)\cup (0,1)$,  tiene un máximo en el punto $(-1,-2)$ y un mínimo en el punto $(1,2)$.

b) Estudio para la función $h(x)=\sqrt{x}-2\sqrt{x+1}$ para $x>0$. La derivada y los ceros de la misma son:
$$
h'(x)=\frac{1}{2\sqrt{x}}-\frac{1}{\sqrt{x+1}},\ \Rightarrow \sqrt{x+1}=2\sqrt{x},\ \Rightarrow x+1=4 x,\ \Rightarrow x=\frac{1}{3}.
$$
Como hemos elevado al cuadrado, tenemos que comprobar que la solución hallada es efectivamente una solución de $h'(x)=0$:
$$
h'\left(\frac{1}{3}\right)=\frac{1}{2\sqrt{\frac{1}{3}}}-\frac{1}{\sqrt{\frac{1}{3}+1}}=\frac{\sqrt{3}}{2}-\frac{1}{\sqrt{\frac{4}{3}}}=\frac{\sqrt{3}}{2}-\frac{\sqrt{3}}{2}=0.
$$
Miremos los intervalos de crecimiento y decrecimiento a partir de la tabla siguiente:
<div class="center">
|$x$| $0$| |$\frac{1}{3}$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|
|$h'$| |$+$| |$-$| |
|$h$| |$\nearrow$| |$\searrow$| |
</div>
La función $h(x)$ crece en el intervalo $\left(0,\frac{1}{3}\right)$, decrece en el intervalo $\left(\frac{1}{3},\infty\right)$ y tiene un máximo en el punto $\left(\frac{1}{3},\sqrt{\frac{1}{3}}-2\sqrt{\frac{1}{3}+1}\right)=\left(\frac{1}{3},-\sqrt{3}\right)$.

c) Estudio para la función $g(x)=\frac{x}{x^2+1}$. La derivada y los ceros de la misma son:
$$
g'(x)=\frac{x^2+1-2x\cdot x}{(x^2+1)^2}=\frac{-x^2+1}{(x^2+1)^2}=0,\ \Rightarrow x=\pm 1.
$$
Miremos los intervalos de crecimiento y decrecimiento a partir de la tabla siguiente:
<div class="center">
|$x$| $-\infty$| |$-1$| |$1$| |$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|$g'$| |$-$| |$+$| |$-$| |
|$g$| |$\searrow$| |$\nearrow$| |$\searrow$| |
</div>
La función $g(x)$ crece en el intervalo $(-1,1)$, decrece en la región $(-\infty,-1)\cup (1,\infty)$, tiene un mínimo en el punto $\left(-1,-\frac{1}{2}\right)$ y un máximo en el punto $\left(1,\frac{1}{2}\right)$.\newpage


5. Sean $a>b>0$ números reales y $n\in\mathbb{N}$ un entero positivo con $n\geq 2$. Demostrar que $a^{\frac{1}{n}}-b^{\frac{1}{n}}< (a-b)^{\frac{1}{n}}$.\newline
Indicación: demostrar que la función $f(x)=x^{\frac{1}{n}}-(x-1)^{\frac{1}{n}}$ es decreciente para $x\geq 1$ y evaluarla en $x=1$ y $x=\frac{a}{b}$.

## Solución

Veamos que la función $f(x)=x^{\frac{1}{n}}-(x-1)^{\frac{1}{n}}$ es decreciente para $x\geq 1$. Si hacemos su derivada obtenemos:
$$
f'(x)=\frac{1}{n}\cdot x^{\frac{1}{n}-1}-\frac{1}{n}\cdot (x-1)^{\frac{1}{n}-1}=\frac{1}{n}\left( x^{\frac{1}{n}-1}-(x-1)^{\frac{1}{n}-1}\right).
$$
Como $\frac{1}{n}-1 <0$ si $n\geq 2$ y como $x\geq x-1$, si $x\geq 1$, tenemos que $x^{\frac{1}{n}-1}< (x-1)^{\frac{1}{n}-1}$. Por tanto, $f'(x)< 0$ y $f(x)$ será decreciente para $x\geq 1$.

Como $a >b$, $\frac{a}{b}>1$ y, como $f(x)$ es decreciente,
$$
f\left(\frac{a}{b}\right) < f(1),\ \Rightarrow \left(\frac{a}{b}\right)^{\frac{1}{n}}-\left(\frac{a}{b}-1\right)^{\frac{1}{n}} < 1,\ \Rightarrow \left(\frac{a}{b}\right)^{\frac{1}{n}}-\left(\frac{a-b}{b}\right)^{\frac{1}{n}} < 1,\ \Rightarrow a^\frac{1}{n}-(a-b)^{\frac{1}{n}}< b^\frac{1}{n},\ \Rightarrow a^\frac{1}{n}-b^\frac{1}{n}< (a-b)^{\frac{1}{n}}.
$$

\newpage

6. Sea $f:[0,2]\longrightarrow \mathbb{R}$, continua en $[0,2]$ y derivable en $(0,2)$. Supongamos que $f(0)=0,\ f(1)=f(2)=1$.
    a) Demostrar que existe un valor $c_1\in (0,1)$ tal que $f'(c_1)=1$.
    a) Demostrar que existe un valor $c_2\in (1,2)$ tal que $f'(c_2)=0$.
    a) Demostrar que existe un valor $c_3\in (0,2)$ tal que $f'(c_3)=\frac{1}{2}$.


## Solución

a) Aplicando el Teorema del valor medio en el intervalo $[0,1]$ tenemos que existe un valor $c_1\in (0,1)$ tal que $$f'(c_1)=\frac{f(1)-f(0)}{1-0}=\frac{1-0}{1}=1.$$

b) Aplicando el Teorema del valor medio en el intervalo $[1,2]$ tenemos que existe un valor $c_2\in (1,2)$ tal que $$f'(c_2)=\frac{f(2)-f(1)}{2-1}=\frac{1-1}{1}=0.$$

c) Aplicando el Teorema del valor medio en el intervalo $[0,2]$ tenemos que existe un valor $c_3\in (0,2)$ tal que $$f'(c_3)=\frac{f(2)-f(0)}{2-0}=\frac{1-0}{2}=\frac{1}{2}.$$



\newpage
7. Usando la regla de L'Hôpital calcular los límites siguientes:
    a) $\displaystyle\lim_{x\to 0}\frac{\mathrm{e}^x+\mathrm{e}^{-x}-2}{1-\cos x}$,
    a) $\displaystyle\lim_{x\to 0}\frac{x^2-\sin^2 x}{x^4}$,
    a) $\displaystyle\lim_{x\to \infty}\frac{x^n}{\mathrm{e}^x}$, con $n$ valor entero, $n\geq 1$,
    a) $\displaystyle\lim_{x\to\frac{\pi}{2}^-}(\sec x-\tan x)$.


## Solución

a) El valor del límite será:
$$
\lim_{x\to 0}\frac{\mathrm{e}^x+\mathrm{e}^{-x}-2}{1-\cos x}=\lim_{x\to 0}\frac{\mathrm{e}^x-\mathrm{e}^{-x}}{\sin x}=\lim_{x\to 0}\frac{\mathrm{e}^x+\mathrm{e}^{-x}}{\cos x}=\frac{2}{1}=2.
$$

b) El valor del límite será:
$$
\begin{array}{rl}
\displaystyle\lim_{x\to 0}\frac{x^2-\sin^2 x}{x^4} &\displaystyle  =\lim_{x\to 0}\frac{2x-2 \sin x\cos x}{4 x^3}=\lim_{x\to 0}\frac{2-2 (\cos^2 x-\sin^2 x)}{12 x^2}=\lim_{x\to 0}\frac{-4 (-\cos x\sin x-\sin x\cos x)}{24 x}\\
& \displaystyle = \lim_{x\to 0}\frac{8 \cos x\sin x}{24 x}=\lim_{x\to 0}\frac{-8 (\sin^2 x}{24 x}
\end{array}
$$

\newpage

8. Descomponer un número $a$ en dos sumandos $x$ e $y$ tal que el valor de $x^2+y^2$ sea mínimo.

9. Determinar las dimensiones que ha de tener un bote cilíndrico de 2 litros de capacidad para que se construya con la cantidad mínima de material.

10. De todos los rectángulos de igual perímetro, ¿cuál es el que tiene área mayor?