---
title: "Problemas de integrales inmediatas."
author: ""
date: ""
output:
  pdf_document: default
              
  html_document: default
---

1. Calcular la siguiente integral inmediata $\displaystyle\int x^2-\sin x\, dx$.

**Solución**

El valor de la integral será:
$$
\int x^2-\sin x\, dx =\frac{x^3}{3}+\cos x+C.
$$
\newpage

2. Calcular la siguiente integral inmediata $\displaystyle\int \mathrm{e}^{3x}+x^4-2\, dx$.

**Solución**

El valor de la integral será:
$$
\int \mathrm{e}^{3x}+x^4-2\, dx =\frac{\mathrm{e}^{3x}}{3}+\frac{x^5}{5}-2x+C.
$$

\newpage


3. Calcular la siguiente integral inmediata $\displaystyle\int 3 t^2+\frac{\ln t}{t}\, dt$.

**Solución**

Usando que $(\ln t)'=\frac{1}{t}$, podemos usar la expresión que dice que $\displaystyle \int f(t)\cdot f'(t)\, dt = \frac{f(t)^2}{2}+C$ y el valor de la integral será:
$$
\int 3 t^2+\frac{\ln t}{t}\, dt =t^3+\frac{(\ln t)^2}{2}+C.
$$
\newpage

4. Calcular la siguiente integral inmediata $\displaystyle\int \tan x-\cos x+\sin (3x)\, dx$.

**Solución**

Usando que $\tan x=\frac{\sin x}{\cos x}=-\frac{(\cos x)'}{\cos x}$ y que $\displaystyle \int \frac{f'(x)}{f(x)}\, dx =\ln |f(x)|+C$, el valor de la integral será:
$$
\int \tan x-\cos x+\sin (3x)\, dx =-\ln|\cos x|-\sin x-\frac{\cos(3x)}{3}+C.
$$
\newpage


5. Calcular la siguiente integral inmediata $\displaystyle\int \cos x\cdot \mathrm{e}^{\sin x}\, dx$.

**Solución**

Usando que en general $\displaystyle \int f'(x)\cdot \mathrm{e}^{f(x)}\, dx=\mathrm{e}^{f(x)}+C$ y que $(\sin x)'=\cos x$, el valor de la integral será:
$$
\int \cos x\cdot \mathrm{e}^{\sin x}\, dx =\mathrm{e}^{\sin x}+C.
$$

\newpage

6. Calcular la siguiente integral inmediata $\displaystyle\int \sin x\cdot \cos x\, dx$.

**Solución**

Usando que $\displaystyle \int f(x)\cdot f'(x)\, dt = \frac{f(x)^2}{2}+C$ y que $(\sin x)'=\cos x$, el valor de la integral será:
$$
\int \sin x\cdot \cos x\, dx =\frac{\sin^2 x}{2}+C.
$$

\newpage

7. Calcular la siguiente integral inmediata $\displaystyle\int \sec^2 x\cdot \mathrm{e}^{\tan x}\, dx$.

**Solución**

Usando que en general $\displaystyle \int f'(x)\cdot \mathrm{e}^{f(x)}\, dx=\mathrm{e}^{f(x)}+C$ y que $(\tan x)'=\frac{1}{\cos^2 x}=\sec^2 x$, el valor de la integral será:
$$
\int \sec^2 x\cdot \mathrm{e}^{\tan x}\, dx =\mathrm{e}^{\tan x}+C.
$$

\newpage

8. Calcular la siguiente integral inmediata $\displaystyle\int (2x+1)\cdot (x^2+x+7)^{43}\, dx$.

**Solución**

Usando que en general $\displaystyle \int f(x)^n\cdot f'(x)\, dx=\frac{f(x)^{n+1}}{n+1}+C$, para $n$ natural, $n\geq 1$, y que $(x^2+x+7)'=2x+1$, el valor de la integral será:
$$
\int (2x+1)\cdot (x^2+x+7)^{43}\, dx =\frac{(x^2+x+7)^{44}}{44}+C.
$$