---
title: "Problemas de integración. Teorema fundamental del cálculo."
author: ""
date: ""
header-includes:
   - \usepackage{polynom}
   - \newtheorem{theorem}{Proposición}
   - \newenvironment{nota}[1]{\vspace{1ex}\textbf{#1}}{\vspace{1ex}}


output:
  pdf_document: default
              
  html_document: default
---

1. Hallar las integrales definidas siguientes:
    a) $\displaystyle\int_0^{\frac{\pi}{4}}\cos^2 x\, dx$.
    a) $\displaystyle\int_0^{1}\frac{x^2}{\sqrt{x^6+4}}\, dx$.
    a) $\displaystyle\int_0^1 \frac{\mathrm{e}^x}{1+\mathrm{e}^{2x}}dx$.
    a) $\displaystyle\int_1^{\mathrm{e}}\frac{\sin(\ln x)}{x}\, dx$.

**Solución**

a) 
$$
\int_0^{\frac{\pi}{4}}\cos^2 x\, dx =\int_0^{\frac{\pi}{4}}\frac{1+\cos (2x)}{2}\, dx=\frac{1}{2}\left[x+\frac{\sin(2x)}{2}\right]_0^{\frac{\pi}{4}}=\frac{1}{2}\left(\frac{\pi}{4}+\frac{1}{2}\sin\frac{\pi}{2}\right)=\frac{\pi}{8}+\frac{1}{4}\approx `r round(pi/8+1/4,4)`.
$$

b) 
$$
\int_0^{1}\frac{x^2}{\sqrt{x^6+4}}\, dx=\frac{1}{3}\int_0^{1}\frac{3x^2}{\sqrt{(x^3)^2+4}}\, dx.
$$
Si hacemos el cambio de variable $t=x^3$, nos queda $dt=3x^2dx$ y la nueva integral en la variable $t$ vale: (si $x=0$, $t=0$ y si $x=1$, $t=1$)
$$
\frac{1}{3}\int_0^1 \frac{dt}{\sqrt{t^2+4}}=\frac{1}{3}[\ln (t+\sqrt{t^2+4})]_0^1 =\frac{1}{3} (\ln(1+\sqrt{5})-\ln (0+2))=\frac{1}{3}\cdot\ln\left(\frac{1+\sqrt{5}}{2}\right)\approx `r round((1/3)*log((1+sqrt(5))/2),4)`.
$$

c) Hacemos el cambio de variable $t=\mathrm{e}^x$, $dt=\mathrm{e}^x dx= tdx,\ dx=\frac{dt}{t}$, si $x=0$, $t=1$ y si $x=1$, $t=\mathrm{e}$:
$$
\int_0^1 \frac{\mathrm{e}^x}{1+\mathrm{e}^{2x}}dx  =\int_1^\mathrm{e} \frac{1}{1+t^2}\, dt=[\arctan t]_1^\mathrm{e} =\arctan\mathrm{e}-\arctan 1=\arctan\mathrm{e}-\frac{\pi}{4}\approx `r round(atan(exp(1))-pi/4,4)`.
$$

d) Hacemos el cambio de variable $t=\ln x$, $dt=\frac{1}{x}\, dx$, para $x=1$, $t=0$ y para $x=\mathrm{e}$, $t=\ln\mathrm{e}=1$:
$$
\int_1^{\mathrm{e}}\frac{\sin(\ln x)}{x}\, dx =\int_{0}^1 \sin t\, dt=[-\cos t]_0^1=-\cos 1+\cos 0=1-\cos 1\approx`r round(1-cos(1),4)`.
$$
\newpage

2. Resolver las integrales siguientes haciendo un cambio de variable adecuado:
    a) $\displaystyle\int_0^4 \frac{1}{1+\sqrt{x}}dx$.
    a) $\displaystyle\int_0^{\ln 5}\frac{\mathrm{e}^x\sqrt{\mathrm{e}^x-1}}{\mathrm{e}^x+3}dx$.


**Solución**

a) Hacemos el cambio siguiente: $t=\sqrt{x}$. Entonces, la relación entre los diferenciales será:
$$
dt=\frac{dx}{2\sqrt{x}}=\frac{dx}{2t},\ \Rightarrow dx=2t\,dt.
$$
Si $x=0$, el valor de la nueva variable $t$ vale $t=\sqrt{0}=0$ y si $x=4$, $t=\sqrt{4}=2$. La integral en la nueva variable $t$ será:
$$
\int_{0}^2 \frac{2t}{1+t}\, dt=2\int_0^2\left(1-\frac{1}{1+t}\right)\,dt =2 [t-\ln(1+t)]_0^2 =2\cdot (2-\ln(3))\approx`r round(2*(2-log(3)),4)`.
$$

b) Hacemos el cambio $t=\sqrt{\mathrm{e}^x-1}$. Entonces, la relación entre los diferenciales será:
$$
dt=\frac{\mathrm{e}^x}{2\sqrt{\mathrm{e}^x-1}}\, dx=\frac{t^2+1}{2t}\, dx,\ \Rightarrow dx=\frac{2t}{t^2+1}\, dt.
$$
Si $x=0$, el valor de la nueva variable $t$ vale $t=\sqrt{\mathrm{e}^{0}-1}=0$ y si $x=\ln 5$, $t=\sqrt{\mathrm{e}^{\ln 5}-1}=\sqrt{5-1}=2$. La integral en la nueva variable $t$ será:
$$
\begin{array}{rl}
\displaystyle\int_0^2 \frac{(t^2+1)\cdot t}{(t^2+1)+3}\cdot \frac{2t}{t^2+1}\, dt & \displaystyle =2\int_0^2\frac{t^2}{t^2+4}\, dt=2\int_0^2\left(1-\frac{4}{t^2+4}\right)\,dt=2\cdot \left[t-2\arctan\left(\frac{t}{2}\right)\right]_0^2\\[0.5cm] & \displaystyle =2\cdot (2-2\cdot \arctan 1) =4\cdot \left(1-\frac{\pi}{4}\right)=4-\pi \approx`r round(4-pi,4)`.
\end{array}
$$
\newpage

3. Resolver las integrales siguientes usando la técnica de integración por partes:
    a) $\displaystyle\int_0^1 x\cdot\mathrm{e}^{-x}\, dx.$
    a) $\displaystyle\int_0^{2\pi} \mathrm{e}^{-a x}\sin (bx)\, dx,$ con $a>0$.
    a) $\displaystyle\int_1^\mathrm{e}x^n\cdot \ln x\, dx,$ con $n\in\mathbb{N}$.
    a) $\displaystyle\int_0^2 x^3\cdot\arctan x\, dx.$

**Solución**

a) Sean
$$
\begin{array}{llcll}
u  &= x,& du &=dx,\\
dv & = \mathrm{e}^{-x}, & v&=-\mathrm{e}^{-x}.
\end{array}
$$
La integral, aplicando la fórmula de integración por partes $\displaystyle \int udv=u\cdot v-\int vdu$, queda:
$$
\begin{array}{rl}
\displaystyle\int_0^1 x\cdot\mathrm{e}^{-x}\, dx & \displaystyle =[-x\cdot\mathrm{e}^{-x}]_0^1+\int_0^1\mathrm{e}^{-x}\, dx=-\mathrm{e}^{-1}-[\mathrm{e}^{-x}]_0^1=-\mathrm{e}^{-1}-(-\mathrm{e}^{-1}-1)\\[0.5cm] & \displaystyle =1-2\cdot\mathrm{e}^{-1}\approx `r round(1-2*exp(-1),4)`.
\end{array}
$$
b) Sean
$$
\begin{array}{llcll}
u  &= \sin(bx),& du &=b\cos(bx)dx,\\
dv & = \mathrm{e}^{-ax}, & v&=-\frac{1}{a}\mathrm{e}^{-ax}.
\end{array}
$$
Aplicando la expresión de integración por partes, la integral anterior será:
$$
\displaystyle\int_0^{2\pi} \mathrm{e}^{-a x}\sin (bx)\, dx = \left[-\frac{1}{a}\sin(bx)\mathrm{e}^{-ax}\right]_0^{2\pi}+\frac{b}{a}\int_0^{2\pi}\mathrm{e}^{-ax}\cos(bx)\,dx.
$$
Volvemos a aplicar la expresión de la integración por partes a la nueva integral que nos ha salido:
$$
\begin{array}{llcll}
u  &= \cos(bx),& du &=-b\sin(bx)dx,\\
dv & = \mathrm{e}^{-ax}, & v&=-\frac{1}{a}\mathrm{e}^{-ax}.
\end{array}
$$
Así, la integral a calcular será:
$$
\begin{array}{rl}
\displaystyle\int_0^{2\pi} \mathrm{e}^{-a x}\sin (bx)\, dx & =\displaystyle \left[-\frac{1}{a}\sin(bx)\mathrm{e}^{-ax}\right]_0^{2\pi}+\frac{b}{a}\int_0^{2\pi}\mathrm{e}^{-ax}\cos(bx)\,dx \\[0.5cm] & \displaystyle = -\frac{1}{a}\sin(2\pi b)\mathrm{e}^{-2\pi a}+\frac{b}{a}\left(\left[-\frac{1}{a}\cos(bx)\mathrm{e}^{-ax}\right]_0^{2\pi}-\frac{b}{a}\int_0^{2\pi}\mathrm{e}^{-ax}\sin(bx)\,dx\right)\\[0.5cm] & \displaystyle = -\frac{1}{a}\sin(2\pi b)\mathrm{e}^{-2\pi a}-\frac{b}{a^2}(\cos(2\pi b)\mathrm{e}^{-2\pi a}-1)-\frac{b^2}{a^2}\int_0^{2\pi}\mathrm{e}^{-ax}\sin(bx)\,dx.
\end{array}
$$
Si despejamos la integral a calcular $\displaystyle \int_0^{2\pi}\mathrm{e}^{-ax}\sin(bx)\,dx$ de la expresión anterior, obtenemos:
$$
\begin{array}{rl}
\displaystyle \left(1+\frac{b^2}{a^2}\right)\int_0^{2\pi}\mathrm{e}^{-ax}\sin(bx)\,dx & \displaystyle = -\frac{1}{a}\sin(2\pi b)\mathrm{e}^{-2\pi a}-\frac{b}{a^2}(\cos(2\pi b)\mathrm{e}^{-2\pi a}-1),\\[0.5cm]
\displaystyle\int_0^{2\pi}\mathrm{e}^{-ax}\sin(bx)\,dx & \displaystyle =\frac{a^2}{a^2+b^2}\left(-\frac{1}{a}\sin(2\pi b)\mathrm{e}^{-2\pi a}-\frac{b}{a^2}(\cos(2\pi b)\mathrm{e}^{-2\pi a}-1)\right), \\[0.5cm]
\displaystyle\int_0^{2\pi}\mathrm{e}^{-ax}\sin(bx)\,dx & \displaystyle =\frac{1}{a^2+b^2}\left(-a\sin(2\pi b)\mathrm{e}^{-2\pi a}-b(\cos(2\pi b)\mathrm{e}^{-2\pi a}-1)\right).
\end{array}
$$

c) Sean
$$
\begin{array}{llcll}
u  &= \ln x,& du &=\frac{1}{x}\,dx,\\
dv & = x^n, & v&=\frac{x^{n+1}}{n+1}.
\end{array}
$$
Aplicando la expresión de integración por partes, la integral anterior será:
$$
\begin{array}{rl}
\displaystyle\int_1^\mathrm{e}x^n\cdot \ln x\, dx & \displaystyle = \frac{1}{n+1}\left[\ln x\cdot x^{n+1}\right]_1^\mathrm{e}-\frac{1}{n+1}\int_1^\mathrm{e}x^n\,dx=\frac{\mathrm{e}^{n+1}}{n+1}-\frac{1}{n+1}\left[\frac{x^{n+1}}{n+1}\right]_1^\mathrm{e}\\[0.5cm] & = \displaystyle \frac{\mathrm{e}^{n+1}}{n+1}-\frac{1}{(n+1)^2}(\mathrm{e}^{n+1}-1)=\mathrm{e}^{n+1}\left(\frac{1}{n+1}-\frac{1}{(n+1)^2}\right)+\frac{1}{(n+1)^2}= \frac{n\mathrm{e}^{n+1}+1}{(n+1)^2}.
\end{array}
$$

d) Sean
$$
\begin{array}{llcll}
u  &= \arctan x,& du &=\frac{1}{1+x^2}\,dx,\\
dv & = x^3, & v&=\frac{x^4}{4}.
\end{array}
$$
Aplicando la expresión de integración por partes, la integral anterior será:
$$
\int_0^2 x^3\cdot\arctan x\, dx =\frac{1}{4}\left[\arctan x\cdot x^4\right]_0^2-\frac{1}{4}\int_0^2 \frac{x^4}{1+x^2}\, dx=4\cdot\arctan 2-\frac{1}{4}\int_0^2 \frac{x^4}{1+x^2}\, dx.
$$
Observamos que nos queda una integral racional $\displaystyle \int_0^2 \frac{x^4}{1+x^2}\, dx$ donde el grado del numerador es mayor que el del denominador. Para resolver este tipo de integrales, primero tenemos que dividir el numerador entre el denominador de cara a transformarla en una integral de tal forma que el grado del numerador sea menor que el del denominador:
$$
\polylongdiv[style=D]{x^4}{x^2+1}
$$
La integral $\displaystyle \int_0^2 \frac{x^4}{1+x^2}\, dx$ se calcula de la forma siguiente:
$$
\begin{array}{rl}
\displaystyle \int_0^2 \frac{x^4}{1+x^2}\, dx & \displaystyle = \int_0^2 (x^2-1)\, dx+\int_0^2 \frac{1}{1+x^2}\, dx=\left[\frac{x^3}{3}-x\right]_0^2+[\arctan x]_0^2 \\[0.5cm] & \displaystyle =\frac{8}{3}-2+\arctan 2 =\frac{2}{3}+\arctan 2.
\end{array}
$$
El valor de la integral pedida será, pues:
$$
\int_0^2 x^3\cdot\arctan x\, dx = 4\cdot\arctan 2-\frac{1}{4}\left(\frac{2}{3}+\arctan 2\right)=\frac{15}{4}\arctan 2-\frac{1}{6}\approx `r round((15/4)*atan(2)-1/6,4)`.
$$

\newpage

4. Hallar los extremos relativos de la función siguiente:
$$
f(x)=\int_0^x \frac{\sin t}{t} \, dt, \ x > 0.
$$

**Solución**

Para hallar los extremos relativos de la función anterior tenemos que derivarla e igualar la función derivada a cero para calcular los candidatos a extremos relativos. Usando el Teorema fundamental del Cálculo, tenemos que la función derivada vale:
$$
f'(x)=\frac{\sin x}{x}.
$$
Los candidatos a extremos relativos cumplen:
$$
f'(x)=\frac{\sin x}{x}=0,\ \Rightarrow \sin x=0,\ \Rightarrow x=\pi n,\ n\in\mathbb{N}.
$$
Veamos si se trata de máximos o mínimos relativos:
<div class="center">
|$x$| |$0$||$\pi$||$2\pi$||$3\pi$||$\ldots$||$2k\pi$||$(2k+1)\pi$||$(2k+2)\pi$||$\ldots$||$\infty$|
|--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|$y'$|||$+$||$-$||$+$||$-$||$\ldots$||$+$||$-$||$+$||$\ldots$
|$y$|||$\nearrow$||$\searrow$||$\nearrow$||$\searrow$||$\ldots$||$\nearrow$||$\searrow$||$\nearrow$||$\ldots$
</div>

Entonces los valores $x_{2k+1}=(2k+1)\pi$, $k\in\mathbb{N}$, corresponden a máximos relativos y los valores $x_{2k}=2k\pi$, $k\in\mathbb{N}$, a mínimos relativos.

\newpage

5. Calcular las derivadas de las funciones siguientes:
    a) $\displaystyle f_1(x) = \int_1^{\ln (x^2+1)} \mathrm{e}^t \> dt.$
    a) $\displaystyle f_2(x) = \int_x^0 \sqrt{1+t^4} \> dt.$
    a) $\displaystyle f_3(x) = \int_{\frac{1}{x}}^{\sqrt{x}} \cos t^2 \> dt.$

**Solución**



Hay que aplicar el resultado que nos da la derivada bajo el signo integral de funciones del tipo:
$$
F(x)=\int_{g(x)}^{h(x)}f(t)\, dt,\quad F'(x)=f(h(x))\cdot h'(x)-f(g(x))\cdot g'(x).
$$

a) Basta considerar $f(x)=\mathrm{e}^x$, $g(x)=1$ y $h(x)=\ln (x^2+1)$:
$$
f_1'(x)=\mathrm{e}^{\ln (x^2+1)}\cdot h'(x) =(x^2+1)\cdot \frac{2x}{x^2+1}=2x,
$$
ya que en este caso $g'(x)=0$ y sólo aparece un término en la expresión de $f_1'(x)$.

b) Basta considerar $f(x)=\sqrt{1+x^4}$, $g(x)=x$ y $h(x)=0$:
$$
f_2'(x)=-\sqrt{1+x^4}\cdot g'(x)=-\sqrt{1+x^4},
$$
ya que en este caso $h'(x)=0$ y sólo aparece un término en la expresión de $f_2'(x)$.

c) Basta considerar $f(x)=\cos(x^2)$, $g(x)=\frac{1}{x}$ y $h(x)=\sqrt{x}$:
$$
f_3'(x)=\cos(\sqrt{x}^2)\cdot h'(x)-\cos\left(\frac{1}{x^2}\right)\cdot g'(x)=\cos(x)\cdot \frac{1}{2\sqrt{x}}-\cos\left(\frac{1}{x^2}\right)\left(-\frac{1}{x^2}\right)=\frac{\cos x}{2\sqrt{x}}+\frac{\cos\left(\frac{1}{x^2}\right)}{x^2}.
$$
