---
title: "Problemas de integración."
author: ""
date: ""
output:
  pdf_document: default
              
  html_document: default
---

1. Consideramos la función $f(x)=x^2$ definida en el intervalo $[0,2]$. Usando una sucesión de particiones $(P_n)_n$ con nodos equiespaciados, calcular la suma inferior y superior $L(f,P_n)$ y $U(f,P_n)$ y demostrar que $\displaystyle\lim_{n\to\infty}L(f,P_n)=\lim_{n\to\infty}U(f,P_n)$. Deducir que $f$ es integrable en el intervalo $[0,2]$ y hallar el valor de la integral $\displaystyle\int_0^2 f$.\newline
Indicación: $\displaystyle\sum_{i=1}^n i^2=\frac{1}{6}n(n+1)(2n+1).$
1. Consideramos la función $f(x)=2^x$ definida en el intervalo $[0,5]$. Usando una sucesión de particiones $(P_n)_n$ con nodos equiespaciados, calcular la suma inferior y superior $L(f,P_n)$ y $U(f,P_n)$ y demostrar que $\displaystyle\lim_{n\to\infty}L(f,P_n)=\lim_{n\to\infty}U(f,P_n)$. Deducir que $f$ es integrable en el intervalo $[0,5]$ y hallar el valor de la integral $\displaystyle\int_0^2 f$.
1. 
    a) Demostrar que, si $g(x)=0$ para $0\leq x\leq {1\over 2}$ y $g(x)=1$ para ${1\over 2}<x\leq 1$,
entonces $\displaystyle\int_0^1 g={1\over 2}$.
    a) ¿Es válida la conclusión si se cambia el valor de $g$ en el punto ${1\over 2}$ por 7?
1. Sea $I=[a,b]$ un intervalo cerrado. Sean $f,g:I\longrightarrow \mathbb{R}$ tales que
difieren sólo en un número finito de puntos. Provar que $f$ es integrable si, y sólo si, lo es $g$ y que se
cumple $\displaystyle\int_a^b f=\int_a^b g$.
1. Sigui $I=[a,b]$ un intervalo cerrado y $f:I\longrightarrow \mathbb{R}$ continua. Supongamos que, para
cualquier función integrable $g:I\longrightarrow \mathbb{R}$, el producto $f\cdot g$ es integrable  $\displaystyle\int_a^b f\cdot g=0$. Demostrar que $f(x)=0$ para todo $x\in I$.

