---
title: "Problemas de integración."
author: ""
date: ""
output:
  pdf_document: default
              
  html_document: default
---

1. Consideramos la función $f(x)=x^2$ definida en el intervalo $[0,2]$. Usando una sucesión de particiones $(P_n)_n$ con nodos equiespaciados, calcular la suma inferior y superior $L(f,P_n)$ y $U(f,P_n)$ y demostrar que $\displaystyle\lim_{n\to\infty}L(f,P_n)=\lim_{n\to\infty}U(f,P_n)$. Deducir que $f$ es integrable en el intervalo $[0,2]$ y hallar el valor de la integral $\displaystyle\int_0^2 f$.\newline
Indicación: $\displaystyle\sum_{i=1}^n i^2=\frac{1}{6}n(n+1)(2n+1).$

**Solución**

Las particiones de nodos equiespaciados y diámetro $\frac{2}{n}$ con $n\in\mathbb{N}$ son las siguientes:
$$
P_n=\left\{x_0=0 <x_1=\frac{2}{n}<\cdots < x_i =\frac{2i}{n}<\cdots <x_n=2\right\}.
$$
La suma inferior $L(f,P_n)$ usando que la función $f(x)$ es creciente en el intervalo $[0,2]$ será:
$$
\begin{array}{rl}
L(f,P_n) & \displaystyle =\sum_{i=1}^n m_i\cdot \frac{2}{n}=\sum_{i=1}^n \inf_{x\in [x_{i-1},x_i]} x^2\cdot \frac{2}{n}=\sum_{i=1}^n \frac{4 (i-1)^2}{n^2}\cdot \frac{2}{n}=\frac{8}{n^3}\sum_{i=1}^{n}(i-1)^2 =\frac{8}{n^3}\sum_{i=1}^{n-1}i^2 \\[0.5cm] & \displaystyle =\frac{8}{n^3}\cdot \frac{1}{6}(n-1)n (2n-1)=\frac{4}{3}\frac{(n-1)(2n-1)}{n^2}.
\end{array}
$$
La suma superior $U(f,P_n)$ usando nuevamente que la función $f(x)$ es creciente en el intervalo $[0,2]$ será:
$$
\begin{array}{rl}
U(f,P_n) & \displaystyle =\sum_{i=1}^n M_i\cdot \frac{2}{n}=\sum_{i=1}^n \sup_{x\in [x_{i-1},x_i]} x^2\cdot \frac{2}{n}=\sum_{i=1}^n \frac{4 i^2}{n^2}\cdot \frac{2}{n}=\frac{8}{n^3}\sum_{i=1}^{n}i^2  =\frac{8}{n^3}\cdot \frac{1}{6}n (n+1) (2n+1)\\[0.5cm]  & \displaystyle =\frac{4}{3}\frac{(n+1)(2n+1)}{n^2}.
\end{array}
$$
Como $\displaystyle\lim_{n\to\infty}L(f,P_n)=\lim_{n\to\infty}U(f,P_n)=\frac{8}{3}$, deducimos que $f$ es integrable y además $\displaystyle \int_0^2 f=\frac{8}{3}.$

\newpage
2. Consideramos la función $f(x)=2^x$ definida en el intervalo $[0,5]$. Usando una sucesión de particiones $(P_n)_n$ con nodos equiespaciados, calcular la suma inferior y superior $L(f,P_n)$ y $U(f,P_n)$ y demostrar que $\displaystyle\lim_{n\to\infty}L(f,P_n)=\lim_{n\to\infty}U(f,P_n)$. Deducir que $f$ es integrable en el intervalo $[0,5]$ y hallar el valor de la integral $\displaystyle\int_0^2 f$.


**Solución**

Las particiones de nodos equiespaciados y diámetro $\frac{5}{n}$ con $n\in\mathbb{N}$ son las siguientes:
$$
P_n=\left\{x_0=0 <x_1=\frac{2}{n}<\cdots < x_i =\frac{5i}{n}<\cdots <x_n=5\right\}.
$$
La suma inferior $L(f,P_n)$ usando que la función $f(x)$ es creciente en el intervalo $[0,5]$ será:
$$
\begin{array}{rl}
L(f,P_n) & \displaystyle =\sum_{i=1}^n m_i\cdot \frac{5}{n}=\sum_{i=1}^n \inf_{x\in [x_{i-1},x_i]} 2^x\cdot \frac{5}{n}=\sum_{i=1}^n 2^{\frac{5(i-1)}{n}}\cdot \frac{5}{n}=\frac{5}{n} \sum_{i=0}^{n-1} 2^{\frac{5 i}{n}}=\frac{5}{n} \sum_{i=0}^{n-1} \left(2^{\frac{5}{n}}\right)^i \\ & \displaystyle =\frac{5}{n}\cdot\frac{\left(2^{\frac{5}{n}\cdot n}-1\right)}{\left(2^{\frac{5}{n}}-1\right)}=\frac{5\cdot 31}{n\left(2^{\frac{5}{n}}-1\right)},
\end{array}
$$
donde hemos usado la igualdad de la suma de la progresión geométrica:
$\displaystyle\sum_{i=0}^{n-1} r^i =\frac{r^n-1}{r-1},$
con $r=2^{\frac{5}{n}}.$

La suma superior $U(f,P_n)$ usando que la función $f(x)$ es creciente en el intervalo $[0,5]$ será:
$$
\begin{array}{rl}
U(f,P_n) & \displaystyle =\sum_{i=1}^n M_i\cdot \frac{5}{n}=\sum_{i=1}^n \sup_{x\in [x_{i-1},x_i]} 2^x\cdot \frac{5}{n}=\sum_{i=1}^n 2^{\frac{5 i}{n}}\cdot \frac{5}{n}=\frac{5}{n} \sum_{i=1}^{n} \left(2^{\frac{5}{n}}\right)^i \\ & \displaystyle =\frac{5}{n}\cdot\frac{\left(2^{\frac{5}{n}\cdot (n+1)}-2^{\frac{5}{n}}\right)}{\left(2^{\frac{5}{n}}-1\right)}=\frac{5}{n}\cdot \frac{\left(2^5 \cdot 2^{\frac{5}{n}}-2^{\frac{5}{n}}\right)}{\left(2^{\frac{5}{n}}-1\right)}=\frac{5}{n}\cdot \frac{2^{\frac{5}{n}}\left(2^5-1\right)}{\left(2^{\frac{5}{n}}-1\right)}=\frac{5\cdot 31\cdot 2^{\frac{5}{n}}}{n\left(2^{\frac{5}{n}}-1\right)},
\end{array}
$$
donde hemos usado la igualdad de la suma de la progresión geométrica:
$\displaystyle\sum_{i=1}^{n} r^i =\frac{r^{n+1}-r}{r-1},$
con $r=2^{\frac{5}{n}}.$

A continuación, calculemos el límite $\displaystyle\lim_{n\to\infty}L(f,P_n)$:
$$
\lim_{n\to\infty}L(f,P_n) =\lim_{n\to\infty}\frac{5\cdot 31}{n\left(2^{\frac{5}{n}}-1\right)}=\lim_{x\to\infty}\frac{5\cdot 31}{x\left(2^{\frac{5}{x}}-1\right)}.
$$
Para resolver el límite anterior, hacemos el cambio $t=\frac{1}{x}$, de esta forma como $x\to\infty$, $t\to 0$. Para calcular el límite que nos queda en función de $t$, aplicamos la regla de l'Hôpital:
$$
\lim_{n\to\infty}L(f,P_n) =\lim_{x\to\infty}\frac{5\cdot 31}{x\left(2^{\frac{5}{x}}-1\right)} =5\cdot 31\cdot\lim_{t\to 0}\frac{t}{2^{5t}-1}=5\cdot 31\cdot\lim_{t\to 0}\frac{1}{2^{5t}\cdot 5\cdot \ln 2}=\frac{31}{\ln 2}.
$$
El límite $\displaystyle\lim_{n\to\infty}U(f,P_n)$ se calcula de forma parecida haciendo el mismo cambio anterior $t=\frac{1}{x}$:
$$
\begin{array}{rl}
\displaystyle\lim_{n\to\infty}U(f,P_n) & \displaystyle =\lim_{n\to\infty}\frac{5\cdot 31\cdot 2^{\frac{5}{n}}}{n\left(2^{\frac{5}{n}}-1\right)}=5\cdot 31\cdot\lim_{x\to\infty}\frac{2^{\frac{5}{x}}}{x\left(2^{\frac{5}{x}}-1\right)}=5\cdot 31\cdot \lim_{t\to 0}\frac{t\cdot 2^{5t}}{\left(2^{5t}-1\right)}\\ &=\displaystyle 5\cdot 31\cdot \lim_{t\to 0}\frac{2^{5t}+t\cdot 2^{5t}\cdot 5\cdot\ln 2}{2^{5t}\cdot 5\cdot \ln 2}=\frac{31}{\ln 2}.
\end{array}
$$
Como los dos límites anteriores son iguales, concluimos que $f$ es integrable en el intervalo $[0,5]$ y además $\displaystyle\int_0^5 f=\frac{31}{\ln 2}.$
\newpage

3. 
    a) Demostrar que, si $g(x)=0$ para $0\leq x\leq {1\over 2}$ y $g(x)=1$ para ${1\over 2}<x\leq 1$,
entonces $\displaystyle\int_0^1 g={1\over 2}$.
    a) ¿Es válida la conclusión si se cambia el valor de $g$ en el punto ${1\over 2}$ por 7?


**Solución**

a) Consideremos la sucesión de particiones siguiente:
$$
P_n=\left\{x_0=0 <x_1=\frac{1}{2n}<\cdots <x_i=\frac{i}{2n}<\cdots < x_n =\frac{n}{2n}=\frac{1}{2}<\cdots <x_{2n}=1\right\}.
$$
Es decir, partimos el intervalo $[0,1]$ en puntos de la forma $\frac{i}{2n}$ para $i=0,\ldots,2n$ ya que de esta forma el valor $\frac{1}{2}$ siempre estará en las particiones anteriores.

La suma inferior $L(f,P_n)$ será la siguiente:
$$
L(f,P_n)  =\sum_{i=1}^{2n} m_i\cdot \frac{1}{2n}=\frac{1}{2n}\cdot\left(\sum_{i=1}^{n} m_i +\sum_{i=n+1}^{2n} m_i\right)=\frac{1}{2n}\sum_{i=n+2}^{2n} 1=\frac{n-1}{2n}.
$$
La suma inferior $U(f,P_n)$ será la siguiente:
$$
U(f,P_n)  =\sum_{i=1}^{2n} M_i\cdot \frac{1}{2n}=\frac{1}{2n}\cdot\left(\sum_{i=1}^{n} M_i +\sum_{i=n+1}^{2n} M_i\right)=\frac{1}{2n}\left(1+\sum_{i=n+1}^{2n} 1\right)=\frac{n+1}{2n}.
$$
Como $\displaystyle\lim_{n\to\infty}L(f,P_n)=\lim_{n\to\infty}U(f,P_n)=\frac{1}{2}$, la función $g$ es integrable en $[0,1]$ y además $\displaystyle\int_0^1 g=\frac{1}{2}$.

b) Si el valor de la función $g$ se cambia de $0$ a $7$, las sumas inferiores y superiores serán:
$$
\begin{array}{rl}
L(f,P_n)   & \displaystyle =\sum_{i=1}^{2n} m_i\cdot \frac{1}{2n}=\frac{1}{2n}\cdot\left(\sum_{i=1}^{n} m_i +\sum_{i=n+1}^{2n} m_i\right)=\frac{1}{2n}\sum_{i=n+2}^{2n} 1=\frac{n-1}{2n}, \\
U(f,P_n) & = \displaystyle \sum_{i=1}^{2n} M_i\cdot \frac{1}{2n}=\frac{1}{2n}\cdot\left(\sum_{i=1}^{n} M_i +\sum_{i=n+1}^{2n} M_i\right)=\frac{1}{2n}\left(7+7+\sum_{i=n+2}^{2n} 1\right)=\frac{14+n-1}{2n}=\frac{13+n}{2n}.
\end{array}
$$
Como también en este caso $\displaystyle\lim_{n\to\infty}L(f,P_n)=\lim_{n\to\infty}U(f,P_n)=\frac{1}{2}$, la función $g$ es integrable en $[0,1]$ y además $\displaystyle\int_0^1 g=\frac{1}{2}$.
\newpage

4. Sea $I=[a,b]$ un intervalo cerrado. Sean $f,g:I\longrightarrow \mathbb{R}$ acotadas tales que
difieren sólo en un número finito de puntos. Provar que $f$ es integrable si, y sólo si, lo es $g$ y que se
cumple $\displaystyle\int_a^b f=\int_a^b g$.

**Solución**

Demostraremos que si $f$ es integrable, entonces también lo es $g$ y además $\displaystyle\int_a^b f=\int_a^b g$.

Para demostrar la otra parte, es decir que si $g$ es integrable, también lo es $f$, basta intercambiar los papeles de $f$ y $g$ en la demostración anterior.

Para demostrar la parte anterior demostraremos la proposición siguiente:

Sean $f,g:I\longrightarrow \mathbb{R}$ tales que difieren sólo en un punto $c$. Entonces si $f$ es integrable, también lo es $g$ y $\displaystyle\int_a^b f=\int_a^b g$.

Fijaos que si demostramos el resultado anterior, tenemos probado lo que pide el problema ya que basta aplicar el resultado un número finito de veces y se obtiene lo que se desea.

Veamos la proposición:

Hemos de demostrar lo siguiente:
$$
\forall \epsilon >0,\ \exists \ \mbox{partición }P\mbox{ tal que }U(g,P)-L(g,P)<\epsilon.
$$

Como $f$ y $g$ están acotadas, existe un valor $K>0$ tal que para todo $x\in I$, $|f(x)-g(x)|\leq K$.

Sabemos que como $f$ es integrable, dado $\epsilon >0$ existe una partición $P$ que podemos suponer que cumple que $|P|<\frac{\epsilon}{2K}$ tal que $U(f,P)-L(f,P)<\frac{\epsilon}{2}.$

Para esta partición $P$, sea $I_c$ el subintervalo de la misma que contiene el punto $c$. Se verifica lo siguiente:
$$
L(g,P)-L(f,P)=(m_{I_c}(g)-m_{I_c}(f))\cdot |I_c|.
$$
El valor $m_{I_c}(g)-m_{I_c}(f)$ estará acotado por $K$. Por tanto:
$$
|L(g,P)-L(f,P)|=|(m_{I_c}(g)-m_{I_c}(f))|\cdot |I_c|\leq K\cdot |P|.
$$
De la misma manera y razonando de forma parecida, tenemos:
$$
|U(g,P)-U(f,P)|=|(M_{I_c}(g)-M_{I_c}(f))|\cdot |I_c|\leq K\cdot |P|.
$$
Por tanto:
$$
\begin{array}{rl}
U(g,P)-L(g,P) & =U(g,P)-U(f,P)+U(f,P)+L(f,P)-L(g,P)-L(f,P)\\ & \leq
|U(g,P)-U(f,P)|+|L(f,P)-L(g,P)|+U(f,P)-L(f,P)\\ & \leq 2K\cdot |P|+\frac{\epsilon}{2}\leq 2K\frac{\epsilon}{2K}+\frac{\epsilon}{2}=\epsilon,
\end{array}
$$
tal como queríamos demostrar.
\newpage

5. Sigui $I=[a,b]$ un intervalo cerrado y $f:I\longrightarrow \mathbb{R}$ continua. Supongamos que, para
cualquier función integrable $g:I\longrightarrow \mathbb{R}$, el producto $f\cdot g$ es integrable  $\displaystyle\int_a^b f\cdot g=0$. Demostrar que $f(x)=0$ para todo $x\in I$.

**Solución**

En particular, como $f$ es continua, será integrable y si aplicamos el resultado del enunciado para $g=f$, tendremos que $\displaystyle \int_a^b f^2 =0$.

Supongamos que existe un valor $x_0\in I$ tal que $f(x_0)\neq 0$. Para este valor $f^2(x_0)>0$. Usando un resultado visto en los apuntes, como $f^2(x)\geq 0$ para todo $x\in I$, se tiene que $\displaystyle\int_a^b f^2 >0$, contradiciendo la hipótesis del enunciado.

Por tanto, $f(x)=0$, para todo $x\in I.$