---
title: "Ejercicios resueltos de derivación. 2a parte."
author: "Juan Gabriel Gomila, Arnau Mir y Llorenç Valverde"
date: ""
output:
  beamer_presentation:
#    colortheme: rose
    incremental: yes
    theme: Warsaw
    toc: no

header-includes: \usepackage{amsmath,color,array,booktabs,algorithm2e}
                 \newcommand\blue[1]{\textcolor{blue}{#1}}
                 \newcommand\red[1]{\textcolor{red}{#1}}
                 

                 
              
---



## Fórmula de Taylor

\begin{block}{Ejercicio 1}
\begin{enumerate}[a)]
\item Desarrollar la función $f(x)=\frac{1}{\sqrt[4]{1+x}}$ en desarrollo de MacLaurin de grado $n$ dando el error cometido.
\item Dar una estimación de $\frac{1}{\sqrt[4]{1.1}}$ con 4 valores exactos.
\end{enumerate}
\end{block}

## Fórmula de Taylor

\begin{block}{\textcolor{green}{Solución}}
\blue{
Apartado a).\pause
\newline
En los apuntes vimos que el desarrollo de Taylor de la función $f(x)=(x+C)^\alpha$ alrededor de $x=x_0$ era:
$$
P_n(x)  = \sum_{k=0}^n \binom{\alpha}{k}\cdot (x_0+C)^{\alpha-k}\cdot (x-x_0)^k,
$$
donde $\binom{\alpha}{k}=\frac{\alpha\cdot (\alpha-1)\cdots (\alpha -k+1)}{k!}$.
}
\end{block}

## Fórmula de Taylor

\begin{block}{\textcolor{green}{Solución}}
\blue{
En nuestro caso, $C=1$, $\alpha=-\frac{1}{4}$ y $x_0=0$:
$$
P_n(x)  = \sum_{k=0}^n \binom{-\frac{1}{4}}{k}\cdot x^k,
$$
\pause
con 
\begin{eqnarray*}
 \binom{-\frac{1}{4}}{k}& = & \frac{-\frac{1}{4}\cdot \left(-\frac{1}{4}-1\right)\cdots \left(-\frac{1}{4}-k+1\right)}{k!}\\ & =&\frac{-\frac{1}{4}\cdot \left(-\frac{5}{4}\right)\cdots \left(-\frac{(4k-3)}{4}\right)}{k!} =\frac{(-1)^k (4k-3)!!!!}{4^k\cdot k!},
\end{eqnarray*}
\pause
donde $i!!!!=i\cdot (i-4)\cdot (i-8)\cdots 1$.\newline\pause
Ejemplos: $5!!!!=5\cdot 1=5$, $8!!!!=8\cdot 4=32$.
}
\end{block}

## Fórmula de Taylor

\begin{block}{\textcolor{green}{Solución}}
\blue{
El desarrollo de Taylor queda de la forma siguiente:
$$
P_n(x)  = \sum_{k=0}^n \frac{(-1)^k (4k-3)!!!!}{4^k\cdot k!}\cdot x^k.
$$
\pause
El error cometido viene dado por la expresión:
\begin{eqnarray*}
R_n(x-x_0) & = & \binom{\alpha}{n+1}\cdot (c+C)^{\alpha-n-1}\cdot  (x-x_0)^{n+1}\\ \pause
&=& \binom{-\frac{1}{4}}{n+1}\cdot (1+c)^{-\frac{1}{4}-n-1}\cdot x^{n+1} \\ \pause
&=& \frac{(-1)^{n+1} (4n+1)!!!!}{4^{n+1}\cdot (n+1)!}\cdot (1+c)^{-n-\frac{5}{4}}\cdot x^{n+1},
\end{eqnarray*}
donde $c\in <0,x>$.
}
\end{block}